# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-21 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GtinRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField(unique=True, verbose_name='Ordem de adoção do range')),
                ('codigo', models.CharField(max_length=5, unique=True, verbose_name='Código identificador do range')),
            ],
            options={
                'db_table': 'fo2_gtin_range',
                'verbose_name': 'Range de GTIN',
            },
        ),
    ]
