# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-22 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(db_index=True, max_length=5, verbose_name='Referência')),
                ('ativo', models.NullBooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Produto',
                'db_table': 'fo2_produto',
            },
        ),
    ]
