# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-22 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoCor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor', models.CharField(db_index=True, max_length=6, verbose_name='Cor')),
                ('ativa', models.BooleanField(default=True)),
                ('imp_cod', models.CharField(max_length=6, verbose_name='Código impresso')),
                ('imp_descr', models.CharField(max_length=6, verbose_name='Descrição impressa')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.Produto', verbose_name='Referência')),
            ],
            options={
                'verbose_name': 'Cor de um produto',
                'db_table': 'fo2_produto_cor',
            },
        ),
    ]
