# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-23 21:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_produtocor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produtocor',
            options={'verbose_name': 'Cor de um produto', 'verbose_name_plural': 'Cores de um produto'},
        ),
    ]
