# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-26 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_produto_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoTamanho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.CharField(db_index=True, max_length=6)),
                ('ativo', models.BooleanField(default=True)),
                ('imp_cod', models.CharField(blank=True, max_length=6, null=True, verbose_name='Código impresso')),
                ('imp_descr', models.CharField(blank=True, max_length=6, null=True, verbose_name='Descrição impressa')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.Produto', verbose_name='Referência')),
            ],
            options={
                'verbose_name': 'Tamanho de um produto',
                'db_table': 'fo2_produto_tamanho',
                'verbose_name_plural': 'Tamanhos de um produto',
            },
        ),
    ]
