# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-27 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_produtotamanho'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='descrição')),
            ],
            options={
                'db_table': 'fo2_composicao',
                'verbose_name': 'Composição',
            },
        ),
    ]
