# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-27 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0006_composicao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComposicaoLinha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField()),
                ('linha', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Linhas da Composição',
                'verbose_name': 'Linha da Composição',
                'db_table': 'fo2_composicao_linha',
            },
        ),
        migrations.AlterModelOptions(
            name='composicao',
            options={'verbose_name': 'Composição', 'verbose_name_plural': 'Composições'},
        ),
        migrations.AddField(
            model_name='composicaolinha',
            name='composicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.Composicao', verbose_name='Composição'),
        ),
    ]
