# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-27 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0008_produto__composicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtocor',
            name='composicao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='produto.Composicao', verbose_name='Composição'),
        ),
    ]
