# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-27 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0010_produto_imagem_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.ImagemTag', verbose_name='Imagem no TAG'),
        ),
    ]
