# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-27 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0011_produto_imagem_tag_typo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtin_tag', models.CharField(blank=True, max_length=13, null=True, verbose_name='GTIN no TAG')),
                ('cor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.ProdutoCor')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.Produto', verbose_name='Referência')),
                ('tamanho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.ProdutoTamanho')),
            ],
            options={
                'verbose_name': 'Item do produto',
                'db_table': 'fo2_produto_item',
                'verbose_name_plural': 'Itens do produto',
            },
        ),
    ]
