# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-27 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0013_produto__campos_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtocor',
            name='composicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produto.Composicao', verbose_name='Composição'),
        ),
    ]
