# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-27 23:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0014_produto_cor__campos_null'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtotamanho',
            name='tamanho',
        ),
    ]
