# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-27 23:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_tamanho'),
        ('produto', '0015_produtotamanho__tamanho_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtotamanho',
            name='tamanho',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='base.Tamanho'),
            preserve_default=False,
        ),
    ]
