# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-29 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0016_produtotamanho__tamanho_foreign'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='cor_no_tag',
            field=models.BooleanField(default=True, verbose_name='Imprime cor no TAG'),
        ),
    ]
