# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-29 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0017_produto_cor_no_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtoitem',
            name='gtin',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='GTIN no XML'),
        ),
    ]
