# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-04-29 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0019_produto_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtocor',
            name='descricao',
            field=models.CharField(default='', max_length=200, verbose_name='descrição'),
        ),
    ]
