# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-04-30 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0022_produtoitem_custo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='ncm',
            field=models.CharField(default='', max_length=8, verbose_name='NCM'),
        ),
    ]
