# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-04-30 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0023_produto_ncm'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='unidade',
            field=models.CharField(default='', max_length=2),
        ),
    ]
