# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-09-01 00:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_requisicao_permission'),
        ('produto', '0027_produto_nivel_validate'),
    ]

    operations = [
        migrations.CreateModel(
            name='GtinLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quando', models.DateTimeField(blank=True, null=True)),
                ('gtin', models.CharField(blank=True, max_length=13, null=True, verbose_name='GTIN no XML')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Colaborador')),
                ('cor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.ProdutoCor')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.Produto', verbose_name='Referência')),
                ('tamanho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.ProdutoTamanho')),
            ],
            options={
                'verbose_name_plural': 'GTIN Log',
                'db_table': 'fo2_prod_gtin_log',
                'permissions': (('can_set_gtin', 'Can set GTIN'),),
            },
        ),
    ]
