# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-18 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import produto.models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0028_gtinlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaTecnica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(db_index=True, max_length=5, verbose_name='Referência')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Inserida em')),
                ('ficha', models.FileField(upload_to=produto.models.ficha_tecnica_upload_to, verbose_name='Ficha técnica')),
                ('habilitada', models.NullBooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ficha técnica',
                'verbose_name_plural': 'Fichas técnicas',
                'db_table': 'fo2_prod_ftec',
            },
        ),
    ]
