# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-18 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0029_fichatecnica'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoFichaTecnica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=10, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Tipo de ficha técnica',
                'verbose_name_plural': 'Tipos de ficha técnica',
                'db_table': 'fo2_prod_ftec_tipo',
            },
        ),
    ]
