# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-18 23:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0030_tipofichatecnica'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichatecnica',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='produto.TipoFichaTecnica'),
        ),
    ]
