# Generated by Django 2.1.15 on 2022-05-10 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0031_fichatecnica_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composicaolinha',
            name='composicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produto.Composicao', verbose_name='Composição'),
        ),
        migrations.AlterField(
            model_name='gtinlog',
            name='cor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produto.ProdutoCor'),
        ),
        migrations.AlterField(
            model_name='gtinlog',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produto.Produto', verbose_name='Referência'),
        ),
        migrations.AlterField(
            model_name='gtinlog',
            name='tamanho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produto.ProdutoTamanho'),
        ),
        migrations.AlterField(
            model_name='produtocor',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produto.Produto', verbose_name='Referência'),
        ),
        migrations.AlterField(
            model_name='produtoitem',
            name='cor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produto.ProdutoCor'),
        ),
        migrations.AlterField(
            model_name='produtoitem',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produto.Produto', verbose_name='Referência'),
        ),
        migrations.AlterField(
            model_name='produtoitem',
            name='tamanho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produto.ProdutoTamanho'),
        ),
        migrations.AlterField(
            model_name='produtotamanho',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produto.Produto', verbose_name='Referência'),
        ),
    ]
