# Generated by Django 2.1.15 on 2022-10-07 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0032_produto_protect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='imagem_tag',
        ),
    ]
