# Generated by Django 3.0.14 on 2022-10-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0033_remove_produto_imagem_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichatecnica',
            name='habilitada',
            field=models.BooleanField(default=True),
        ),
    ]
