# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImpressoraTermica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome')),
            ],
            options={
                'db_table': 'fo2_lot_impr_termica',
                'verbose_name': 'impressora térmica',
                'verbose_name_plural': 'impressoras térmicas',
            },
        ),
        migrations.CreateModel(
            name='ModeloTermica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='código')),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='nome')),
                ('modelo', models.TextField(blank=True, null=True, verbose_name='modelo')),
                ('campos', models.TextField(blank=True, null=True, verbose_name='campos')),
            ],
            options={
                'db_table': 'fo2_lot_modelo_termica',
                'verbose_name': 'modelo de etiqueta térmica',
                'verbose_name_plural': 'modelos de etiqueta térmica',
            },
        ),
    ]
