# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impresso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Impresso',
                'db_table': 'fo2_lot_impresso',
            },
        ),
    ]
