# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 15:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lotes', '0002_impresso'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioImpresso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impresso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotes.Impresso', verbose_name='impresso')),
                ('impressora_termica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotes.ImpressoraTermica', verbose_name='impressora térmica')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotes.ModeloTermica', verbose_name='modelo padrão')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name_plural': 'Impressos de usuários',
                'verbose_name': 'Impressos de usuário',
                'db_table': 'fo2_lot_usuario_impresso',
            },
        ),
    ]
