# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 15:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lotes', '0003_usuarioimpresso'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usuarioimpresso',
            unique_together=set([('usuario', 'impresso')]),
        ),
    ]
