# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-08 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0004_auto_20170929_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelotermica',
            name='receita',
            field=models.CharField(blank=True, max_length=4096, null=True, verbose_name='receita'),
        ),
    ]
