# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-08 18:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0005_modelotermica_receita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelotermica',
            name='modelo',
        ),
    ]
