# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-23 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0006_remove_modelotermica_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelotermica',
            name='receita',
            field=models.CharField(blank=True, max_length=8192, null=True, verbose_name='receita'),
        ),
    ]
