# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-23 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0008_modelotermica_gabarito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelotermica',
            name='receita',
        ),
    ]
