# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-28 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0009_remove_modelotermica_receita'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(max_length=20, verbose_name='lote')),
                ('op', models.IntegerField(blank=True, null=True, verbose_name='OP')),
                ('referencia', models.CharField(max_length=5, verbose_name='Referência')),
                ('tamanho', models.CharField(max_length=3, verbose_name='Tamanho')),
                ('cor', models.CharField(max_length=6, verbose_name='Cor')),
                ('qtd_produzir', models.IntegerField(verbose_name='quantidade')),
                ('create_at', models.DateTimeField(blank=True, null=True, verbose_name='criado em')),
                ('update_at', models.DateTimeField(blank=True, null=True, verbose_name='alterado em')),
            ],
            options={
                'db_table': 'fo2_cd_lote',
                'verbose_name': 'lote',
            },
        ),
    ]
