# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-29 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0010_lote'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='ordem_tamanho',
            field=models.SmallIntegerField(default=0, verbose_name='ordem tamanho'),
        ),
    ]
