# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-29 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0011_lote_ordem_tamanho'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caixa', models.CharField(max_length=20)),
                ('tipo_doc', models.CharField(choices=[('o', 'OP'), ('a', 'Avulsa')], default='o', max_length=1, verbose_name='tipo de documento')),
                ('id_doc', models.CharField(blank=True, max_length=64, null=True, verbose_name='identificador do documento')),
                ('ordem', models.IntegerField(blank=True, null=True, verbose_name='ordem da caixa')),
                ('ativa', models.NullBooleanField(default=True)),
                ('create_at', models.DateTimeField(blank=True, null=True, verbose_name='criada em')),
                ('update_at', models.DateTimeField(blank=True, null=True, verbose_name='alterado em')),
            ],
            options={
                'db_table': 'fo2_cd_caixa',
                'verbose_name': 'caixa',
            },
        ),
    ]
