# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-29 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0012_caixa'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='caixa',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='lotes.Caixa'),
        ),
    ]
