# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-16 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0013_lote_caixa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='ordem_tamanho',
            field=models.IntegerField(default=0, verbose_name='ordem tamanho'),
        ),
    ]
