# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-16 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0014_auto_20180416_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='local',
            field=models.CharField(default='', max_length=3),
        ),
    ]
