# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-18 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0015_lote_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='local',
            field=models.CharField(default=None, max_length=3),
        ),
    ]
