# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-18 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0016_auto_20180418_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='local_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='localizado em'),
        ),
    ]
