# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-19 12:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lotes', '0018_auto_20180419_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='local_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='localizado por'),
        ),
    ]
