# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-27 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0019_lote_local_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lote',
            options={'permissions': (('can_inventorize_lote', 'Can inventorize lote'), ('can_relocate_lote', 'Can relocate lote')), 'verbose_name': 'lote'},
        ),
    ]
