# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-30 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0020_auto_20180427_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='local',
            field=models.CharField(blank=True, default=None, max_length=3, null=True),
        ),
    ]
