# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-08 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0021_auto_20180430_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='trail',
            field=models.IntegerField(default=0),
        ),
    ]
