# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-15 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0023_auto_20180508_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='local',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=3, null=True),
        ),
    ]
