# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-15 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0024_auto_20180515_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='local_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='localizado em'),
        ),
    ]
