# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-15 23:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lotes', '0025_auto_20180515_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitaLote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='código')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True, verbose_name='descrição')),
                ('ativa', models.NullBooleanField(default=True)),
                ('create_at', models.DateTimeField(blank=True, null=True, verbose_name='criado em')),
                ('update_at', models.DateTimeField(blank=True, null=True, verbose_name='alterado em')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'Solicitação de lote',
                'db_table': 'fo2_cd_solicita_lote',
            },
        ),
    ]
