# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-17 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0026_solicitalote'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitaLoteQtd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd', models.IntegerField(default=0, verbose_name='quantidade solicitada')),
                ('create_at', models.DateTimeField(blank=True, null=True, verbose_name='criado em')),
                ('update_at', models.DateTimeField(blank=True, null=True, verbose_name='alterado em')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lotes.Lote', verbose_name='Lote')),
                ('solicitacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lotes.SolicitaLote', verbose_name='Solicitação')),
            ],
            options={
                'db_table': 'fo2_cd_solicita_lote_qtd',
                'verbose_name': 'Quantidades Solicitadas de lotes',
            },
        ),
    ]
