# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-30 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0027_solicitaloteqtd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Op',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op', models.IntegerField(verbose_name='OP')),
                ('pedido', models.IntegerField()),
                ('varejo', models.BooleanField(default=False)),
                ('cancelada', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'fo2_prod_op',
            },
        ),
    ]
