# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-03 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0028_op'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='lote',
            field=models.CharField(db_index=True, max_length=20, verbose_name='lote'),
        ),
    ]
