# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-03 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0029_auto_20180903_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='cor',
            field=models.CharField(db_index=True, max_length=6, verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='create_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='estagio',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='lote',
            name='op',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='OP'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='ordem_tamanho',
            field=models.IntegerField(db_index=True, default=0, verbose_name='ordem tamanho'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='referencia',
            field=models.CharField(db_index=True, max_length=5, verbose_name='Referência'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='tamanho',
            field=models.CharField(db_index=True, max_length=3, verbose_name='Tamanho'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='update_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='alterado em'),
        ),
    ]
