# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-02-26 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0030_auto_20180903_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='local',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=4, null=True),
        ),
    ]
