# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-28 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0031_local_length_4'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='op',
            options={'permissions': (('can_repair_seq_op', 'Can repair sequence OP'),)},
        ),
    ]
