# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-06-15 03:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0034_solicitaloteqtd_initialize_when'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lote',
            options={'permissions': (('can_inventorize_lote', 'Can inventorize lote'), ('can_relocate_lote', 'Can relocate lote'), ('can_uninventorize_road', 'Can uninventorize road')), 'verbose_name': 'lote'},
        ),
    ]
