# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-07-10 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0035_auto_20190615_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadColecao',
            fields=[
                ('colecao', models.IntegerField(primary_key=True, serialize=False, verbose_name='Coleção')),
                ('lead', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': 'Lead de produção',
                'db_table': 'fo2_lot_lead_colecao',
            },
        ),
    ]
