# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-02 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0036_leadcolecao'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadcolecao',
            name='lm_tam',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Lote mínimo por tamanho'),
        ),
    ]
