# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-09 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0038_leadcolecao_lm_cor'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraLeadTamanho',
            fields=[
                ('tamanho', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Tamanho')),
                ('min_para_lm', models.IntegerField(blank=True, default=0, null=True, verbose_name='% mínimo para aplicação do lote mínimo por tamanho')),
                ('lm_cor_sozinha', models.CharField(default='s', max_length=1, verbose_name='Aplica lote mínimo por cor quando único tamanho')),
            ],
            options={
                'verbose_name': 'Regra de Lead por tamanho',
                'db_table': 'fo2_lot_regra_lead_tamanho',
            },
        ),
    ]
