# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-09 19:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0040_regraleadtamanho_ordem_tamanho'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegraLeadTamanho',
            new_name='RegraLMTamanho',
        ),
    ]
