# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-09 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0041_rename_RegraLMTamanho'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regralmtamanho',
            options={'verbose_name': 'Regra de lote mínimo por tamanho'},
        ),
        migrations.AlterModelTable(
            name='regralmtamanho',
            table='fo2_lot_regra_lm_tamanho',
        ),
    ]
