# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-29 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0042_rename_fo2_lot_regra_lm_tamanho'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotesPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('can_edit_estagio_direito', 'Can edit direitos a estágios'),),
                'managed': False,
            },
        ),
    ]
