# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-14 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0043_lotespermissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitalote',
            name='data',
            field=models.DateField(blank=True, null=True, verbose_name='Data do embarque'),
        ),
    ]
