# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-17 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0044_solicitalote_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadcolecao',
            options={'verbose_name': 'Lead de produção', 'verbose_name_plural': 'Leads de produção'},
        ),
    ]
