# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-01 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0045_lot_lead_colecao_plural'),
    ]

    operations = [
        migrations.AddField(
            model_name='op',
            name='deposito',
            field=models.IntegerField(default=-1),
        ),
    ]
