# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-01 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0046_op_deposito'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='op_obj',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='lotes.Op'),
        ),
    ]
