# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-01 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0048_lote_op_obj_init'),
    ]

    operations = [
        migrations.AddField(
            model_name='impresso',
            name='slug',
            field=models.SlugField(default='a'),
            preserve_default=False,
        ),
    ]
