# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-01 21:22
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils.text import slugify


def migrate_data_forward(apps, schema_editor):
    Impresso = apps.get_model('lotes', 'Impresso')
    for instance in Impresso.objects.all():
        instance.slug = slugify(instance.nome)
        instance.save()


def migrate_data_backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0049_impresso_slug'),
    ]

    operations = [
        migrations.RunPython(
            migrate_data_forward,
            migrate_data_backward,
        ),
    ]
