# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-02 19:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lotes', '0050_impresso_slug_init'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitaLotePrinted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printed_at', models.DateTimeField(blank=True, null=True, verbose_name='etiquetas impressas em')),
                ('printed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='etiquetas impressas por')),
                ('solicitacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lotes.SolicitaLote', verbose_name='Solicitação')),
            ],
            options={
                'verbose_name': 'Impressão de solicitação de lotes',
                'verbose_name_plural': 'Impressões de solicitações de lotes',
                'db_table': 'fo2_cd_solicita_lote_prt',
            },
        ),
    ]
