# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-02 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0051_solicitaloteprinted'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitalote',
            name='can_print',
            field=models.BooleanField(default=True),
        ),
    ]
