# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-10-09 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0057_solicitalote_conluida'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitalote',
            old_name='conluida',
            new_name='concluida',
        ),
    ]
