# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-10-13 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0059_can_reabrir_solicitacao_completada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lotespermissions',
            options={'managed': False, 'permissions': (('can_edit_estagio_direito', 'Can edit direitos a estágios'), ('can_print__solicitacao_parciais', 'Pode imprimir etiquetas de solicitações parciais'), ('can_reabrir_solicitacao_completada', 'Pode reabrir solicitação marada como completa'), ('libera_coleta_de_solicitacao', 'Libera coleta de solicitação'))},
        ),
    ]
