# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-10-16 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0060_libera_coleta_de_solicitacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='op',
            name='sync',
            field=models.IntegerField(default=-1),
        ),
    ]
