# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-10-16 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0061_op_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='op',
            name='sync_id',
            field=models.IntegerField(default=-1),
        ),
    ]
