# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-11-13 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0062_op_sync_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnderecoDispovivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.CharField(max_length=4, unique=True, verbose_name='Início do endereço')),
            ],
            options={
                'verbose_name': 'Endereço disponível',
                'verbose_name_plural': 'Endereços disponível',
                'db_table': 'fo2_cd_endereco_disponivel',
            },
        ),
    ]
