# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-11-13 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0063_enderecodispovivel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EnderecoDispovivel',
            new_name='EnderecoDisponivel',
        ),
    ]
