# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-11-27 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0066_lote_sync_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='sync',
            field=models.IntegerField(default=-1),
        ),
    ]
