# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-19 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0068_enderecodisponivel_verbose'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LeadColecao',
            new_name='RegraColecao',
        ),
    ]
