# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-19 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0069_leadcolecao_regracolecao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regracolecao',
            options={'verbose_name': 'Regra por coleção', 'verbose_name_plural': 'Regras por coleção'},
        ),
        migrations.AlterModelTable(
            name='regracolecao',
            table='fo2_lot_regra_colecao',
        ),
    ]
