# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-19 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0070_regracolecao_table_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='regracolecao',
            name='referencia',
            field=models.CharField(default='', max_length=5, verbose_name='Referência'),
        ),
    ]
