# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-19 16:15
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0071_regracolecao_referencia'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='regracolecao',
            managers=[
                ('objects_referencia', django.db.models.manager.Manager()),
            ],
        ),
    ]
