# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-19 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0072_regracolecao_objects_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='regracolecao',
            name='id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
