# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-19 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0075_regracolecao_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regracolecao',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
