# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-19 21:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0076_regracolecao_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='regracolecao',
            unique_together=set([('colecao', 'referencia')]),
        ),
    ]
