# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-19 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0079_regracolecao_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regracolecao',
            name='referencia',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name='Referência'),
        ),
    ]
