# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-25 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0081_regracolecao_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lotespermissions',
            options={'managed': False, 'permissions': (('can_edit_estagio_direito', 'Can edit direitos a estágios'), ('can_print__solicitacao_parciais', 'Pode imprimir etiquetas de solicitações parciais'), ('can_reabrir_solicitacao_completada', 'Pode reabrir solicitação marada como completa'), ('libera_coleta_de_solicitacao', 'Libera coleta de solicitação'), ('manutencao-de-regra-de-lote-por-caixa', 'Manutenção de regra de lote por caixa'))},
        ),
    ]
