# Generated by Django 2.1.15 on 2021-08-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0082_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='enderecodisponivel',
            name='disponivel',
            field=models.BooleanField(default=True, verbose_name='Disponível'),
        ),
    ]
