# Generated by Django 2.1.15 on 2021-10-20 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0083_enderecodisponivel_disponivel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='op',
            options={'permissions': (('can_repair_seq_op', 'Can repair sequence OP'), ('can_reactivate_op', 'Can reactivate OP'))},
        ),
    ]
