# Generated by Django 2.1.15 on 2021-10-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0084_op_can_reactivate_op'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='local',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=5, null=True),
        ),
    ]
