# Generated by Django 2.1.15 on 2022-03-24 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0086_can_reactivate_pedido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lotespermissions',
            options={'managed': False, 'permissions': (('can_edit_estagio_direito', 'Can edit direitos a estágios'), ('can_print__solicitacao_parciais', 'Pode imprimir etiquetas de solicitações parciais'), ('can_reabrir_solicitacao_completada', 'Pode reabrir solicitação marada como completa'), ('libera_coleta_de_solicitacao', 'Libera coleta de solicitação'), ('manutencao-de-regra-de-lote-por-caixa', 'Manutenção de regra de lote por caixa'), ('can_reactivate_pedido', 'Can reactivate pedido'), ('prepara-pedidos-filial-matriz', 'Prepara pedidos Filial->Matriz'))},
        ),
    ]
