# Generated by Django 2.1.15 on 2022-03-28 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0088_permission_bug_prepara_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioimpresso',
            name='impresso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lotes.Impresso', verbose_name='impresso'),
        ),
        migrations.AlterField(
            model_name='usuarioimpresso',
            name='impressora_termica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lotes.ImpressoraTermica', verbose_name='impressora térmica'),
        ),
        migrations.AlterField(
            model_name='usuarioimpresso',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lotes.ModeloTermica', verbose_name='modelo padrão'),
        ),
        migrations.AlterField(
            model_name='usuarioimpresso',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
    ]
