# Generated by Django 2.1.15 on 2022-05-10 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0089_usuario_impresso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='caixa',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='lotes.Caixa'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='local_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='localizado por'),
        ),
    ]
