# Generated by Django 2.1.15 on 2022-05-10 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0090_lotes_protect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitalote',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.AlterField(
            model_name='solicitaloteprinted',
            name='printed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='etiquetas impressas por'),
        ),
        migrations.AlterField(
            model_name='solicitaloteprinted',
            name='solicitacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lotes.SolicitaLote', verbose_name='Solicitação'),
        ),
        migrations.AlterField(
            model_name='solicitaloteqtd',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lotes.Lote', verbose_name='Lote'),
        ),
        migrations.AlterField(
            model_name='solicitaloteqtd',
            name='solicitacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lotes.SolicitaLote', verbose_name='Solicitação'),
        ),
    ]
