# Generated by Django 2.1.15 on 2022-05-26 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lotes', '0091_lotes_protect'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioLote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(db_index=True, max_length=9)),
                ('quantidade', models.IntegerField(default=0)),
                ('quando', models.DateTimeField(verbose_name='informado em')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='informado por')),
            ],
            options={
                'verbose_name': 'Inventário de lote',
                'db_table': 'fo2_inventario_lote',
            },
        ),
    ]
