# Generated by Django 2.1.15 on 2022-05-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0092_inventariolote'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariolote',
            name='diferenca',
            field=models.IntegerField(blank=True, null=True, verbose_name='direrença'),
        ),
    ]
