# Generated by Django 2.1.15 on 2022-05-30 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0094_inventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariolote',
            name='inventario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lotes.Inventario', verbose_name='inventário'),
        ),
    ]
