# Generated by Django 2.1.15 on 2022-05-30 20:45

from django.db import migrations, models
from django.utils import timezone


def do(apps, schema_editor):
    inventario = apps.get_model("lotes", "Inventario")
    inventario(
        inicio=timezone.now()
    ).save()


def undo(apps, schema_editor):
    inventario = apps.get_model("lotes", "Inventario")
    inventario.objects.all().delete() 


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0095_inventariolote_inventario'),
    ]

    operations = [
        migrations.RunPython(
            do, undo),
    ]
