# Generated by Anselmo on 2022-05-30 21:07

from django.db import migrations, models
from django.utils import timezone


def do(apps, schema_editor):
    Inventario = apps.get_model("lotes", "Inventario")
    InventarioLote = apps.get_model("lotes", "InventarioLote")
    inventario = Inventario.objects.last()
    for inv_lote in InventarioLote.objects.all():
        inv_lote.inventario = inventario
        inv_lote.save()


def undo(apps, schema_editor):
    InventarioLote = apps.get_model("lotes", "InventarioLote")
    for inv_lote in InventarioLote.objects.all():
        inv_lote.inventario = None
        inv_lote.save()


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0096_create_first_inventario'),
    ]

    operations = [
        migrations.RunPython(
            do, undo),
    ]
