# Generated by Django 2.1.15 on 2022-05-30 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0097_set_inventariolote_inventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariolote',
            name='inventario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lotes.Inventario', verbose_name='inventário'),
        ),
    ]
