# Generated by Django 2.1.15 on 2022-05-31 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0098_inventariolote_inventario_not_null'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventariolote',
            unique_together={('lote', 'quando')},
        ),
    ]
