# Generated by Django 3.0.14 on 2022-10-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0100_permission_informa_nf_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='ativa',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='solicitalote',
            name='ativa',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='solicitaloteqtd',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='apagado'),
        ),
    ]
