# Generated by Django 3.2.16 on 2023-02-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0101_boolean'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpCortada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op', models.IntegerField(verbose_name='OP')),
            ],
            options={
                'verbose_name': 'OPs cortadas',
                'db_table': 'fo2_op_cortada',
            },
        ),
    ]
