# Generated by Django 3.2.16 on 2023-02-06 07:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0102_opcortada'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcortada',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='apagado'),
        ),
        migrations.AddField(
            model_name='opcortada',
            name='origin_id',
            field=models.IntegerField(default=0, verbose_name='id de origem'),
        ),
        migrations.AddField(
            model_name='opcortada',
            name='unique_aux',
            field=models.IntegerField(default=0, verbose_name='campo auxiliar para unique_together'),
        ),
        migrations.AddField(
            model_name='opcortada',
            name='version',
            field=models.IntegerField(default=0, verbose_name='versão'),
        ),
        migrations.AddField(
            model_name='opcortada',
            name='when',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='quando'),
        ),
    ]
