# Generated by Django 3.2.16 on 2023-02-06 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0103_auto_20230206_0711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opcortada',
            options={'verbose_name': 'OP cortada', 'verbose_name_plural': 'OPs cortadas'},
        ),
    ]
