# Generated by Django 3.2.16 on 2023-02-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0104_alter_opcortada_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcortada',
            name='original_when',
            field=models.DateTimeField(blank=True, null=True, verbose_name='quando original'),
        ),
    ]
