# Generated by Django 3.2.16 on 2023-02-06 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0105_opcortada_original_when'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opcortada',
            old_name='original_when',
            new_name='origin_when',
        ),
    ]
