# Generated by Django 3.2.16 on 2023-02-06 08:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0107_alter_opcortada_origin_when'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcortada',
            name='origin_when',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='quando de origem'),
        ),
    ]
