# Generated by Django 3.2.16 on 2023-02-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0108_alter_opcortada_origin_when'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcortada',
            name='origin_when',
            field=models.DateTimeField(blank=True, null=True, verbose_name='quando de origem'),
        ),
    ]
