# Generated by Django 3.2.16 on 2023-02-06 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_delete_imagemtag'),
        ('lotes', '0109_alter_opcortada_origin_when'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcortada',
            name='colaborador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='base.colaborador'),
            preserve_default=False,
        ),
    ]
