# Generated by Django 3.2.16 on 2023-02-06 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lotes', '0111_alter_opcortada_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcortada',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='user_table_heap', to='auth.user', verbose_name='usuário'),
            preserve_default=False,
        ),
    ]
