# Generated by Django 3.2.16 on 2023-02-06 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lotes', '0112_opcortada_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcortada',
            name='origin_user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='origin_user_table_heap', to='auth.user', verbose_name='usuário de origem'),
            preserve_default=False,
        ),
    ]
