# Generated by Django 3.2.16 on 2023-02-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0114_alter_opcortada_origin_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opcortada',
            name='unique_aux',
        ),
        migrations.AddField(
            model_name='opcortada',
            name='origin_version',
            field=models.IntegerField(default=0, verbose_name='versão de origem'),
        ),
    ]
