# Generated by Django 3.2.16 on 2023-02-06 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0117_alter_opcortada_origin_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opcortada',
            name='origin_user',
        ),
        migrations.RemoveField(
            model_name='opcortada',
            name='origin_version',
        ),
        migrations.RemoveField(
            model_name='opcortada',
            name='origin_when',
        ),
    ]
