# Generated by Django 3.2.16 on 2023-02-06 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0118_auto_20230206_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opcortada',
            name='deleted',
        ),
    ]
