# Generated by Django 3.2.16 on 2023-02-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0121_auto_20230206_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcortada',
            name='pedido_filial',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
