# Generated by Django 3.2.16 on 2023-03-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0122_opcortada_pedido_filial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcortada',
            name='evento',
            field=models.CharField(choices=[('C', 'OP cortada'), ('F', 'Pedido de venda da filial para a matriz'), ('M', 'Pedido de compra na matriz'), ('N', 'Gera NF de pedido da filial'), ('R', 'Recebe NF da filial na matriz')], default='C', max_length=1),
        ),
    ]
