# Generated by Django 3.2.16 on 2023-03-03 14:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_delete_imagemtag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lotes', '0123_opcortada_evento'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OpCortada',
            new_name='OpComCorte',
        ),
    ]
