# Generated by Django 3.2.16 on 2023-03-03 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0124_rename_opcortada_opcomcorte'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='opcomcorte',
            table='fo2_op_com_corte',
        ),
    ]
