# Generated by Django 3.2.16 on 2023-03-03 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0125_alter_opcomcorte_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opcomcorte',
            options={'permissions': (('pode_marcar_op_como_cortada', 'Pode marcar OP como cortada'),), 'verbose_name': 'OP com corte', 'verbose_name_plural': 'OPs com corte'},
        ),
    ]
