# Generated by Django 3.2.16 on 2023-03-03 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0126_alter_opcomcorte_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opcomcorte',
            name='evento',
        ),
    ]
