# Generated by Django 3.2.16 on 2023-03-03 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0128_opcomcorte_delete_rows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opcomcorte',
            name='colaborador',
        ),
    ]
