# Generated by Django 3.2.16 on 2023-03-03 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_delete_imagemtag'),
        ('lotes', '0129_remove_opcomcorte_colaborador'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcomcorte',
            name='cortado_colab',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='base.colaborador', verbose_name='Cortado colaborador'),
            preserve_default=False,
        ),
    ]
