# Generated by Django 3.2.16 on 2023-03-03 15:59

from django.db import migrations


def delete_rows(apps, schema_editor):
    OpComCorte = apps.get_model('lotes', 'OpComCorte')
    OpComCorte.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0132_opcomcorte_pedidofilial_rename_pedidofmnum'),
    ]

    operations = [
        migrations.RunPython(delete_rows),
    ]
