# Generated by Django 3.2.16 on 2023-03-03 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0133_opcomcorte_delete_rows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opcomcorte',
            name='cortado_colab',
        ),
        migrations.RemoveField(
            model_name='opcomcorte',
            name='cortado_quando',
        ),
    ]
