# Generated by Django 3.2.16 on 2023-03-03 18:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_delete_imagemtag'),
        ('lotes', '0134_opcomcorte_exclui_campos'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcomcorte',
            name='cortada_colab',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='base.colaborador', verbose_name='Cortada colaborador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opcomcorte',
            name='cortada_quando',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Cortada quando'),
        ),
    ]
