# Generated by Django 3.2.16 on 2023-03-03 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_delete_imagemtag'),
        ('lotes', '0135_opcomcorte_inclui_campos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcomcorte',
            name='cortada_colab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='op_cortada_colab', to='base.colaborador', verbose_name='Cortada colaborador'),
        ),
    ]
