# Generated by Django 3.2.16 on 2023-03-03 19:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0137_opcomcorte_pedido_fm_colab'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcomcorte',
            name='pedido_fm_quando',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Pedido-FM quando'),
        ),
    ]
