# Generated by Django 3.2.16 on 2023-03-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0138_opcomcorte_pedido_fm_quando'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcomcorte',
            name='pedido_fm_quando',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Pedido-FM quando'),
        ),
    ]
