# Generated by Django 3.2.16 on 2023-03-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0140_alter_opcomcorte_pedido_fm_colab'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcomcorte',
            name='pedido_cm_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pedido de compra da Matriz'),
        ),
    ]
