# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-14 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CsrfToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(blank=True, null=True)),
                ('token', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'CSRF Token utilizado',
                'verbose_name_plural': 'CSRF Tokens utilizados',
                'db_table': 'o2_csrf_token',
            },
        ),
    ]
