# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-14 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('o2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csrftoken',
            name='token',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
