# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-23 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoImagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(db_index=True)),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição')),
            ],
            options={
                'db_table': 'fo2_tipo_imagem',
                'verbose_name_plural': 'Tipos de imagem',
                'verbose_name': 'Tipo de imagem',
            },
        ),
    ]
