# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-26 17:42
from __future__ import unicode_literals

import base.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_fo2_tipo_imagem_loaddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('slug', models.SlugField()),
                ('imagem', models.ImageField(upload_to=base.models.upload_to)),
                ('tipo_imagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.TipoImagem', verbose_name='Tipo da imagem')),
            ],
            options={
                'verbose_name': 'Imagem',
                'db_table': 'fo2_imagem',
                'verbose_name_plural': 'Imagens',
            },
        ),
    ]
