# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-27 20:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemTag',
            fields=[
            ],
            options={
                'indexes': [],
                'verbose_name_plural': 'Imagens para TAG',
                'verbose_name': 'Imagem para TAG',
                'proxy': True,
            },
            bases=('base.imagem',),
        ),
    ]
