# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-27 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_imagemtag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tamanho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=3)),
                ('ordem', models.IntegerField()),
            ],
            options={
                'db_table': 'fo2_tamanho',
                'verbose_name': 'Tamanho',
            },
        ),
    ]
