# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-07-05 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_colaborador'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='colaborador',
            table='fo2_colaborador',
        ),
    ]
