# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-02 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_typo_fo2_colaborador'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colaborador',
            options={'permissions': (('can_generate_product_stages', 'Can generate product stages'), ('can_adjust_stock', 'Can adjust stock'))},
        ),
    ]
