# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-23 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20191202_1729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colaborador',
            options={'permissions': (('can_generate_product_stages', 'Can generate product stages'), ('can_adjust_stock', 'Can adjust stock')), 'verbose_name_plural': 'Colaboradores'},
        ),
        migrations.AddField(
            model_name='colaborador',
            name='cpf',
            field=models.CharField(default=0, max_length=11, unique=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='matricula',
            field=models.CharField(default='00000', max_length=5, unique=True, verbose_name='matrícula'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
