# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-07 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_fo2_colaborador_obs'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='logged',
            field=models.BooleanField(default=False),
        ),
    ]
