# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-08 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_colaborador_logged'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='quando',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
