# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-11 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_colaborador_quando'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='ip_interno',
            field=models.BooleanField(default=False),
        ),
    ]
