# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-10-16 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_requisicao_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncDelTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Sincronização de deleção - Tabela',
                'db_table': 'fo2_sync_del_table',
            },
        ),
    ]
