# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-10-16 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_syncdeltable'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncDel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_id', models.IntegerField()),
                ('tabela', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.SyncDelTable')),
            ],
            options={
                'verbose_name': 'Sincronização de deleção',
                'db_table': 'fo2_sync_del',
            },
        ),
    ]
