# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-17 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_colaborador_urser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='número')),
                ('nome', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Empresa',
                'db_table': 'fo2_empresa',
            },
        ),
    ]
