# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-17 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='numero',
            field=models.IntegerField(unique=True, verbose_name='número'),
        ),
    ]
