# Generated by Django 2.1.15 on 2021-08-02 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_syncdel_tussor_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='syncdel',
            old_name='tussor_id',
            new_name='sync_id',
        ),
    ]
