# Generated by Django 2.1.15 on 2021-09-21 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_syncdel_sync_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicao',
            name='colaborador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.Colaborador'),
        ),
    ]
