# Generated by Django 2.1.15 on 2022-01-24 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_imagem_caminho'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TipoImagem',
            new_name='GrupoArquivo',
        ),
    ]
