# Generated by Django 2.1.15 on 2022-01-24 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_tipo_imagem_to_grupo_arquivo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='grupoarquivo',
            table='fo2_grupo_arquivo',
        ),
    ]
