# Generated by Django 2.1.15 on 2022-01-24 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_fo2_grupo_arquivo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupoarquivo',
            options={'verbose_name': 'Grupo de arquivo', 'verbose_name_plural': 'Grupos de arquivo'},
        ),
    ]
