# Generated by Django 2.1.15 on 2022-01-24 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_grupo_arquivo_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='tipo_imagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens_tipo', to='base.GrupoArquivo', verbose_name='Tipo da imagem'),
        ),
    ]
