# Generated by Django 2.1.15 on 2022-01-24 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_imagem_related_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagem',
            name='grupo_arquivo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='base.GrupoArquivo', verbose_name='Grupo do arquivo'),
        ),
    ]
