# Generated by Django 2.1.15 on 2022-01-24 15:30

from django.db import migrations


def populate_grupo_arquivo(apps, schema_editor):
    Imagem = apps.get_model("base", "Imagem")
    for imagem in Imagem.objects.all():
        imagem.grupo_arquivo = imagem.tipo_imagem
        imagem.save()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_imagem_grupo_arquivo'),
    ]

    operations = [
        migrations.RunPython(populate_grupo_arquivo, migrations.RunPython.noop),
    ]
