# Generated by Django 2.1.15 on 2022-01-24 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_imagem_grupo_arquivo_no_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagem',
            name='tipo_imagem',
        ),
    ]
