# Generated by Django 2.1.15 on 2022-01-24 15:59

import base.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_remove_imagem_tipo_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('slug', models.SlugField()),
                ('caminho', models.CharField(default='', max_length=255)),
                ('arquivo', models.FileField(upload_to=base.models.documento_upload_to)),
                ('grupo_arquivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.GrupoArquivo', verbose_name='Grupo do arquivo')),
            ],
            options={
                'verbose_name': 'Documento',
                'db_table': 'fo2_documento',
            },
        ),
    ]
