# Generated by Django 2.1.15 on 2022-10-07 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_base_protect'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagemTag',
        ),
    ]
