# Generated by Django 3.2.16 on 2023-03-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_colaborador_cd_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='cd_bonus',
            field=models.BooleanField(default=False, verbose_name='Participa do bônus do CD'),
        ),
    ]
