# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-19 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dis_dup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_dupnum', models.CharField(db_index=True, max_length=7)),
                ('d_fatnum', models.IntegerField()),
                ('d_cgc', models.CharField(max_length=14)),
                ('d_pednum', models.IntegerField()),
                ('d_valor', models.DecimalField(decimal_places=2, max_digits=9)),
                ('d_dvenc', models.DateField()),
                ('d_dfat', models.DateField()),
                ('d_dcanc', models.DateField()),
                ('d_dpago', models.DateField()),
                ('d_vpago', models.DecimalField(decimal_places=2, max_digits=9)),
                ('d_icm', models.IntegerField()),
                ('d_stat', models.CharField(max_length=1)),
                ('d_statori', models.CharField(max_length=1)),
                ('d_op', models.CharField(max_length=2)),
                ('d_banco', models.CharField(max_length=3)),
                ('d_desconto', models.CharField(max_length=1)),
                ('d_cpag', models.CharField(max_length=1)),
                ('d_cond', models.IntegerField()),
                ('d_qtd', models.IntegerField()),
                ('d_qtdfat', models.IntegerField()),
                ('d_caixas', models.IntegerField()),
                ('d_pesbru', models.DecimalField(decimal_places=2, max_digits=7)),
                ('d_juros', models.DecimalField(decimal_places=2, max_digits=5)),
                ('d_desc', models.DecimalField(decimal_places=2, max_digits=4)),
                ('d_descf1', models.DecimalField(decimal_places=2, max_digits=4)),
                ('d_descf2', models.DecimalField(decimal_places=2, max_digits=4)),
                ('d_tipdescf', models.CharField(max_length=1)),
                ('d_repr', models.CharField(max_length=4)),
                ('d_comi', models.DecimalField(decimal_places=1, max_digits=3)),
                ('d_codfis', models.CharField(max_length=4)),
                ('d_transp', models.CharField(max_length=2)),
                ('d_pc', models.DecimalField(decimal_places=4, max_digits=10)),
                ('d_protest', models.CharField(max_length=1)),
                ('d_especial', models.CharField(max_length=1)),
                ('d_777', models.DecimalField(decimal_places=2, max_digits=9)),
                ('d_qtd777', models.IntegerField()),
                ('d_obs', models.CharField(max_length=14)),
                ('d_aux', models.CharField(max_length=1)),
                ('d_978', models.DecimalField(decimal_places=2, max_digits=9)),
                ('d_qtd978', models.IntegerField()),
                ('rec_ver', models.IntegerField()),
                ('d_tipocanc', models.IntegerField()),
                ('d_prortip', models.CharField(max_length=1)),
                ('calc_cgc', models.CharField(max_length=8)),
                ('d_modfrete', models.CharField(max_length=1)),
                ('f_f1', models.CharField(max_length=1)),
                ('d_repr2', models.CharField(max_length=3)),
                ('d_dentr', models.DateField()),
                ('d_dsaida', models.DateField()),
                ('d_snagenda', models.CharField(max_length=1)),
                ('d_snentreg', models.CharField(max_length=1)),
                ('d_dxmlsent', models.DateField()),
                ('d_dtrem', models.DateField()),
                ('d_arqrem', models.CharField(max_length=8)),
                ('d_dvencori', models.DateField()),
                ('d_dvencrem', models.DateField()),
                ('d_dxmlsend', models.DateField()),
                ('d_xmlenvia', models.CharField(max_length=1)),
                ('d_obsentr', models.CharField(max_length=80)),
                ('d_descfat', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
            options={
                'db_table': 'tussor_dis_dup',
            },
        ),
    ]
