# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-19 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tussor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dis_cli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_cgc', models.CharField(db_index=True, max_length=14)),
                ('c_rsoc', models.CharField(max_length=40)),
                ('c_end', models.CharField(max_length=40)),
                ('c_bairro', models.CharField(max_length=25)),
                ('c_munic', models.CharField(max_length=25)),
                ('c_telex', models.CharField(max_length=25)),
                ('c_ddd', models.CharField(max_length=4)),
                ('c_tel', models.CharField(max_length=20)),
                ('c_uf', models.CharField(max_length=2)),
                ('c_cep', models.CharField(max_length=9)),
                ('c_inest', models.CharField(max_length=18)),
                ('c_lc', models.CharField(max_length=1)),
                ('c_repr', models.CharField(max_length=3)),
                ('c_desde', models.DateField()),
                ('c_sufr', models.CharField(max_length=15)),
                ('c_banco', models.CharField(max_length=3)),
                ('c_obs', models.CharField(max_length=60)),
                ('c_obs2', models.CharField(max_length=60)),
                ('c_obs3', models.CharField(max_length=60)),
                ('c_display', models.IntegerField()),
                ('c_disdata', models.DateField()),
                ('cc_cgc', models.CharField(max_length=14)),
                ('cc_rsoc', models.CharField(max_length=40)),
                ('cc_end', models.CharField(max_length=40)),
                ('cc_bairro', models.CharField(max_length=25)),
                ('cc_munic', models.CharField(max_length=25)),
                ('cc_telex', models.CharField(max_length=25)),
                ('cc_inest', models.CharField(max_length=18)),
                ('cc_tel', models.CharField(max_length=20)),
                ('cc_ddd', models.CharField(max_length=4)),
                ('cc_uf', models.CharField(max_length=2)),
                ('cc_cep', models.CharField(max_length=9)),
                ('rec_ver', models.IntegerField()),
                ('c_isento', models.CharField(max_length=1)),
                ('c_le', models.CharField(max_length=10)),
                ('ce_cgc', models.CharField(max_length=14)),
                ('ce_inest', models.CharField(max_length=18)),
                ('ce_rsoc', models.CharField(max_length=40)),
                ('ce_cep', models.CharField(max_length=9)),
                ('ce_end', models.CharField(max_length=40)),
                ('ce_bairro', models.CharField(max_length=25)),
                ('ce_munic', models.CharField(max_length=25)),
                ('ce_uf', models.CharField(max_length=2)),
                ('c_endok', models.CharField(max_length=1)),
                ('malaok', models.CharField(max_length=1)),
                ('c_transp', models.CharField(max_length=2)),
                ('origem', models.CharField(max_length=1)),
                ('c_email', models.CharField(max_length=100)),
                ('c_email2', models.CharField(max_length=100)),
                ('dadosok', models.CharField(max_length=1)),
                ('seleciona', models.CharField(max_length=1)),
                ('f_f1', models.CharField(max_length=1)),
                ('c_repr2', models.CharField(max_length=3)),
                ('calc_cgc', models.CharField(max_length=8)),
                ('c_piscof', models.CharField(max_length=1)),
                ('c_tipo', models.CharField(max_length=1)),
                ('c_cmun', models.CharField(max_length=7)),
                ('ce_cmun', models.CharField(max_length=7)),
                ('cc_cmun', models.CharField(max_length=7)),
            ],
            options={
                'db_table': 'tussor_dis_cli',
            },
        ),
    ]
