-- sequence - auto inc utilizado para:
--   ids de registros: _ID
--   versões de registros: _SYNC nas tabelas e ID no log de deleção
CREATE SEQUENCE SYSTEXTIL.FO2_TUSSOR INCREMENT BY 1 MINVALUE 1
NOCYCLE CACHE 1000 NOORDER;
COMMIT;

-- tabela que guarda ids de registros apagados em tabelas
CREATE TABLE SYSTEXTIL.FO2_TUSSOR_SYNC_DEL (
  ID INTEGER NOT NULL,
  TABELA VARCHAR2(100) NOT NULL,
  SYNC_ID INTEGER NOT NULL,
  QUANDO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
TABLESPACE SYSTEXTIL_DADOS;
COMMIT;

COMMENT ON COLUMN SYSTEXTIL.FO2_TUSSOR_SYNC_DEL.ID IS
  'Flag de deleção: campo analisado em uma sincronização, para achar as deleções mais recentes';
COMMENT ON COLUMN SYSTEXTIL.FO2_TUSSOR_SYNC_DEL.TABELA IS
  'Nome da tabela alvo de uma deleção';
COMMENT ON COLUMN SYSTEXTIL.FO2_TUSSOR_SYNC_DEL.SYNC_ID IS
  'Id imutável do registro apagado na tabela indicada';
COMMENT ON COLUMN SYSTEXTIL.FO2_TUSSOR_SYNC_DEL.QUANDO IS
  'Quando a deleção ocorreu';

-- o índice é o ID
ALTER TABLE SYSTEXTIL.FO2_TUSSOR_SYNC_DEL ADD (
  CONSTRAINT FO2_TUSSOR_SYNC_DEL_PK PRIMARY KEY (ID));
COMMIT;

-- trigger para atribuir valor ao ID
CREATE OR REPLACE TRIGGER SYSTEXTIL.FO2_TUSSOR_SYNC_DEL_TR
BEFORE INSERT ON SYSTEXTIL.FO2_TUSSOR_SYNC_DEL
FOR EACH ROW
BEGIN
  SELECT SYSTEXTIL.FO2_TUSSOR.NEXTVAL
  INTO   :new.id
  FROM   dual;
END FO2_TUSSOR_SYNC_DEL_TR;

-- preparando tebela PCPC_020 para trabalhar com ID e SYNC do FO2

ALTER TABLE SYSTEXTIL.PCPC_020 ADD FO2_TUSSOR_ID INTEGER;
ALTER TABLE SYSTEXTIL.PCPC_020 ADD FO2_TUSSOR_SYNC INTEGER;
COMMIT;

COMMENT ON COLUMN SYSTEXTIL.PCPC_020.FO2_TUSSOR_SYNC IS
  'Campo específico da Tussor: flag de alteração';
COMMENT ON COLUMN SYSTEXTIL.PCPC_020.FO2_TUSSOR_ID IS
  'Campo específico da Tussor: id imutável';

-- trigger para logar deleção nesta tabela
CREATE OR REPLACE TRIGGER SYSTEXTIL.TUSSOR_TR_PCPC_020_SYNC_DEL
  AFTER DELETE
  ON SYSTEXTIL.PCPC_020
  FOR EACH ROW
BEGIN
  INSERT INTO FO2_TUSSOR_SYNC_DEL (TABELA, SYNC_ID)
  VALUES ('PCPC_020', :old.FO2_TUSSOR_ID);
END TUSSOR_TR_PCPC_020_SYNC_DEL;

-- trigger para atribuir valor ao ID imutável e ao SYNC
CREATE OR REPLACE TRIGGER SYSTEXTIL.TUSSOR_TR_PCPC_020_SYNC
  BEFORE INSERT OR UPDATE
  ON SYSTEXTIL.PCPC_020
  FOR EACH ROW
DECLARE
  v_sync SYSTEXTIL.PCPC_020.FO2_TUSSOR_SYNC%TYPE;
BEGIN
  SELECT SYSTEXTIL.FO2_TUSSOR.NEXTVAL
  INTO   v_sync
  FROM   DUAL;
  IF INSERTING or :old.FO2_TUSSOR_ID is NULL THEN
    :new.FO2_TUSSOR_ID := v_sync;
  ELSE
    :new.FO2_TUSSOR_ID := :old.FO2_TUSSOR_ID;
  END IF;
  :new.FO2_TUSSOR_SYNC := v_sync;
END TUSSOR_TR_PCPC_020_SYNC
;

-- após a criação das triggers, acerta os registros anteriores à trigger
UPDATE SYSTEXTIL.PCPC_020
SET FO2_TUSSOR_ID = NULL
WHERE FO2_TUSSOR_ID IS NULL;
COMMIT;
