# Generated by Django 2.1.15 on 2021-11-22 15:42

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colecao',
            fields=[
                ('colecao', models.IntegerField(primary_key=True, serialize=False)),
                ('descr_colecao', models.CharField(max_length=100, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Coleção',
                'db_table': 'BASI_140',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContaEstoque',
            fields=[
                ('conta_estoque', models.IntegerField(primary_key=True, serialize=False, verbose_name='Código')),
                ('descr_ct_estoque', models.CharField(max_length=100, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Conta de estoque',
                'db_table': 'BASI_150',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('codigo_empresa', models.IntegerField(primary_key=True, serialize=False, verbose_name='codigo')),
                ('nome_fantasia', models.CharField(max_length=20, verbose_name='nome')),
            ],
            options={
                'db_table': 'FATU_500',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('divisao_producao', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=20, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Família',
                'db_table': 'BASI_180',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HDoc001',
            fields=[
                ('tipo', models.IntegerField()),
                ('codigo', models.IntegerField(primary_key=True, serialize=False, verbose_name='Código')),
                ('descricao', models.CharField(max_length=60, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tabela auxiliar HDOC_001',
                'db_table': 'HDOC_001',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LinhaNivel1',
            fields=[
                ('linha_produto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Linha')),
                ('nivel_estrutura', models.IntegerField(verbose_name='Nível')),
                ('descricao_linha', models.CharField(max_length=20, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Linha de Produto Nível 1',
                'db_table': 'BASI_120',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('area_periodo', models.IntegerField(verbose_name='Área do período')),
                ('periodo_producao', models.IntegerField(verbose_name='Período de produção')),
                ('data_ini_periodo', models.DateTimeField(primary_key=True, serialize=False, verbose_name='Data inicial do período')),
                ('data_fim_periodo', models.DateTimeField(verbose_name='Data final do período')),
            ],
            options={
                'verbose_name': 'Período',
                'db_table': 'PCPC_010',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('nivel_estrutura', models.CharField(max_length=1, verbose_name='Nível')),
                ('referencia', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Referência')),
            ],
            options={
                'verbose_name': 'Produto (Systêxtil)',
                'db_table': 'BASI_030',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tamanho',
            fields=[
                ('tamanho_ref', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Código')),
                ('descr_tamanho', models.CharField(max_length=10, verbose_name='Descrição')),
                ('ordem_tamanho', models.IntegerField(verbose_name='Ordem do tamanho')),
            ],
            options={
                'verbose_name': 'Tamanho (Systêxtil)',
                'db_table': 'BASI_220',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoTransacao',
            fields=[
                ('codigo_transacao', models.IntegerField(primary_key=True, serialize=False, verbose_name='Código da transação')),
                ('descricao', models.CharField(max_length=20, verbose_name='Descrição')),
                ('entrada_saida', models.CharField(max_length=1, verbose_name='Entrada/Saída')),
            ],
            options={
                'verbose_name': 'Código de transação de estoque',
                'db_table': 'ESTQ_005',
                'managed': False,
            },
            managers=[
                ('validos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Usuário')),
                ('empresa', models.IntegerField()),
                ('codigo_usuario', models.IntegerField(verbose_name='Código do Usuário')),
                ('ativo_inativo', models.IntegerField(verbose_name='Ativo ou inativo')),
            ],
            options={
                'verbose_name': 'Usuário',
                'db_table': 'HDOC_030',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoContaEstoque',
            fields=[
            ],
            options={
                'verbose_name': 'Tipo de conta de estoque',
                'db_table': 'HDOC_001',
                'managed': False,
                'proxy': True,
            },
            bases=('systextil.hdoc001',),
        ),
    ]
