# Generated by Django 2.1.15 on 2021-11-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systextil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystextilPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('can_be_dba', 'Can be DBA'),),
                'managed': False,
            },
        ),
    ]
