# Generated by Django 2.1.15 on 2022-02-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systextil', '0002_systextilpermissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estagio',
            fields=[
                ('codigo_estagio', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=20, verbose_name='Descrição')),
                ('leed_time', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'verbose_name': 'Estágio',
                'db_table': 'MQOP_005',
                'managed': False,
            },
        ),
    ]
