# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecordTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64, verbose_name='Usuário')),
                ('time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Hora')),
                ('table', models.CharField(max_length=64, verbose_name='Tabela')),
                ('record_id', models.IntegerField(verbose_name='Id do registro')),
                ('iud', models.CharField(max_length=1, verbose_name='Ação')),
                ('log', models.CharField(max_length=2048, verbose_name='Log')),
            ],
            options={
                'verbose_name_plural': 'logs de registro de tabela',
                'verbose_name': 'log de registro',
                'db_table': 'fo2_ger_record_tracking',
            },
        ),
    ]
