# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0002_auto_20170914_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, verbose_name='Chave de identificação')),
                ('nome', models.CharField(blank=True, max_length=64, null=True, verbose_name='Nome do dispositivo')),
            ],
            options={
                'db_table': 'fo2_ger_dispositivos',
                'verbose_name': 'dispositivo',
            },
        ),
    ]
