# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0003_dispositivos'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoloBipado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolo', models.IntegerField(verbose_name='Código de barras')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('referencia', models.CharField(max_length=5, verbose_name='Referência')),
                ('tamanho', models.CharField(max_length=3, verbose_name='Tamanho')),
                ('cor', models.CharField(max_length=6, verbose_name='Cor')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geral.Dispositivos')),
            ],
            options={
                'verbose_name': 'rolo bipado',
                'verbose_name_plural': 'rolos bipados',
                'db_table': 'fo2_ger_rolo_bipado',
            },
        ),
    ]
