# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-08 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0004_rolobipado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolobipado',
            name='rolo',
            field=models.IntegerField(verbose_name='Rolo'),
        ),
    ]
