# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-15 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0005_auto_20171208_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Painel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'painel',
                'db_table': 'fo2_ger_painel',
            },
        ),
        migrations.CreateModel(
            name='PainelModulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=64, null=True)),
                ('tipo', models.CharField(choices=[('I', 'Informativo')], default='I', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'modulos de painel',
                'verbose_name': 'modulo de painel',
                'db_table': 'fo2_ger_painel_modulo',
            },
        ),
    ]
