# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-15 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0006_painel_painelmodulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='painel',
            name='layout',
            field=models.CharField(blank=True, max_length=4096, null=True, verbose_name='receita'),
        ),
    ]
