# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-18 14:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geral', '0007_painel_layout'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioPainelModulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('painel_modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geral.PainelModulo', verbose_name='módulo de painel')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'db_table': 'fo2_ger_usr_pnl_modulo',
                'verbose_name_plural': 'usuáios de modulos de painel',
                'verbose_name': 'usuáio de modulo de painel',
            },
        ),
    ]
