# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-18 15:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geral', '0008_usuariopainelmodulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformacaoModulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data')),
                ('chamada', models.CharField(blank=True, max_length=200, null=True, verbose_name='chamada')),
                ('texto', models.CharField(blank=True, max_length=4096, null=True, verbose_name='receita')),
                ('painel_modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geral.PainelModulo', verbose_name='módulo de painel')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
        ),
    ]
