# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-20 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0010_painel_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='painel',
            options={'verbose_name': 'painel', 'verbose_name_plural': 'paineis'},
        ),
        migrations.AlterModelOptions(
            name='usuariopainelmodulo',
            options={'verbose_name': 'usuário de modulo de painel', 'verbose_name_plural': 'usuários de modulos de painel'},
        ),
        migrations.AddField(
            model_name='painelmodulo',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
