# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-20 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0011_auto_20171220_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacaomodulo',
            name='habilitado',
            field=models.NullBooleanField(default=True),
        ),
    ]
