# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-23 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0012_informacaomodulo_habilitado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordtracking',
            name='log',
            field=models.CharField(max_length=65535, verbose_name='Log'),
        ),
    ]
