# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-19 21:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0016_auto_20180419_1719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolobipado',
            options={'permissions': (('can_beep_rolo', 'Can beep rolo'),), 'verbose_name': 'rolo bipado', 'verbose_name_plural': 'rolos bipados'},
        ),
    ]
