# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-22 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0017_auto_20180419_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopAssunto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255)),
                ('diretorio', models.CharField(blank=True, max_length=50, verbose_name='diretório')),
            ],
        ),
    ]
