# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-22 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0018_popassunto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pop',
            name='assunto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='geral.PopAssunto', verbose_name='assunto do POP'),
        ),
    ]
