# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-23 15:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import geral.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geral', '0020_popassunto_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioPopAssunto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geral.PopAssunto', verbose_name='assunto de POP')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'usuário de assunto de POP',
                'verbose_name_plural': 'usuários de assuntos de POPs',
                'db_table': 'fo2_ger_usr_pop_assunto',
            },
        ),
        migrations.AlterField(
            model_name='pop',
            name='pop',
            field=models.FileField(upload_to=geral.models.pop_upload_to, verbose_name='Arquivo POP'),
        ),
    ]
