# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-02-11 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0021_auto_20190123_1315'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='informacaomodulo',
            table='fo2_ger_modulo_info',
        ),
        migrations.AlterModelTable(
            name='pop',
            table='fo2_ger_doc',
        ),
        migrations.AlterModelTable(
            name='popassunto',
            table='fo2_ger_doc_assunto',
        ),
        migrations.AlterModelTable(
            name='usuariopopassunto',
            table='fo2_ger_usr_doc_assunto',
        ),
    ]
