# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-02-11 13:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0022_renaming_tables'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pop',
            table='fo2_ger_pop',
        ),
        migrations.AlterModelTable(
            name='popassunto',
            table='fo2_ger_pop_assunto',
        ),
        migrations.AlterModelTable(
            name='usuariopopassunto',
            table='fo2_ger_usr_pop_assunto',
        ),
    ]
