# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-02-13 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0023_return_renaming_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='popassunto',
            name='grupo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='popassunto',
            name='grupo_slug',
            field=models.SlugField(default='slug'),
        ),
    ]
