# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-04-30 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0024_pop_assunto_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordtracking',
            name='record_id',
            field=models.IntegerField(db_index=True, verbose_name='Id do registro'),
        ),
    ]
