# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-05-15 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0025_0025_fo2_ger_record_tracking__record_id__index'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoParametro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5, unique=True, verbose_name='código')),
                ('descricao', models.CharField(max_length=255, unique=True, verbose_name='descrição')),
            ],
            options={
                'db_table': 'fo2_param_tipo',
            },
        ),
    ]
