# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-23 18:57
from __future__ import unicode_literals

from django.db import migrations, models


def load_tipoparametro_from_fixture(apps, schema_editor):
    from django.core.management import call_command
    call_command("loaddata", "0027_tipoparametro_loaddata")


def delete_tipoparametro(apps, schema_editor):
    TipoImagem = apps.get_model("base", "TipoParametro ")
    TipoImagem.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0026_tipoparametro'),
    ]

    operations = [
        migrations.RunPython(
            load_tipoparametro_from_fixture, delete_tipoparametro),
    ]
