# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-05-15 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0027_tipoparametro_loaddata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoparametro',
            options={'verbose_name': 'Tipo de parâmetro', 'verbose_name_plural': 'Tipos de parâmetros'},
        ),
    ]
