# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-05-15 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0030_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametro',
            name='ajuda',
            field=models.CharField(blank=True, max_length=65535, null=True),
        ),
    ]
