# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-05-17 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0033_painel_habilitado'),
    ]

    operations = [
        migrations.AddField(
            model_name='painelmodulo',
            name='habilitado',
            field=models.NullBooleanField(default=True),
        ),
    ]
