# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-07 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0034_painelmodulo_habilitado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painelmodulo',
            name='tipo',
            field=models.CharField(choices=[('I', 'Informativo'), ('C', 'URL de cartaz em imagem')], default='I', max_length=1),
        ),
    ]
