# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-10-01 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0035_painelmodulo_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordtracking',
            name='log_version',
            field=models.SmallIntegerField(default=1, verbose_name='Versão do log'),
        ),
    ]
