# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-14 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0036_recordtracking_log_version'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='recordtracking',
            index_together=set([('time', 'table', 'record_id')]),
        ),
    ]
