# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-16 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0037_recordtracking_index_together'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='recordtracking',
            index=models.Index(fields=['-id'], name='fo2_ger_record_track_desc_id'),
        ),
    ]
