# Generated by Django 2.1.15 on 2021-09-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0038_recordtracking_index_desc_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacaomodulo',
            name='chamada',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='chamada'),
        ),
    ]
