# Generated by Django 2.1.15 on 2022-05-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0039_informacaomodulo_chamada'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopGrupoAssunto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(default='slug')),
            ],
            options={
                'db_table': 'fo2_ger_pop_grup_assu',
            },
        ),
    ]
