# Generated by Django 2.1.15 on 2022-05-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0040_popgrupoassunto'),
    ]

    operations = [
        migrations.AddField(
            model_name='popgrupoassunto',
            name='ordem',
            field=models.IntegerField(default=0),
        ),
    ]
