# Generated by Django 2.1.15 on 2022-05-10 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0044_popassunto_grupo_assunto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popassunto',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='popassunto',
            name='grupo_slug',
        ),
    ]
