# Generated by Django 2.1.15 on 2022-05-10 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0045_popassunto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='parametro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geral.Parametro'),
        ),
        migrations.AlterField(
            model_name='config',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.AlterField(
            model_name='informacaomodulo',
            name='painel_modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geral.PainelModulo', verbose_name='módulo de painel'),
        ),
        migrations.AlterField(
            model_name='informacaomodulo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geral.TipoParametro'),
        ),
        migrations.AlterField(
            model_name='pop',
            name='assunto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='geral.PopAssunto', verbose_name='assunto do POP'),
        ),
        migrations.AlterField(
            model_name='rolobipado',
            name='dispositivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='geral.Dispositivos'),
        ),
        migrations.AlterField(
            model_name='rolobipado',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.AlterField(
            model_name='usuariopainelmodulo',
            name='painel_modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geral.PainelModulo', verbose_name='módulo de painel'),
        ),
        migrations.AlterField(
            model_name='usuariopainelmodulo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.AlterField(
            model_name='usuariopopassunto',
            name='assunto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geral.PopAssunto', verbose_name='assunto de POP'),
        ),
        migrations.AlterField(
            model_name='usuariopopassunto',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
    ]
