# Generated by Django 3.2.16 on 2023-06-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0049_auto_20221011_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMaquina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, unique=True, verbose_name='descrição')),
            ],
            options={
                'verbose_name': 'Tipo de máquina',
                'verbose_name_plural': 'Tipos de máquinas',
                'db_table': 'fo2_maquina_tipo',
            },
        ),
    ]
