# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-17 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMovStq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('trans_saida', models.IntegerField(default=0, verbose_name='Transação de saída')),
                ('trans_entrada', models.IntegerField(default=0, verbose_name='Transação de entrada')),
            ],
            options={
                'verbose_name': 'Tipo de movimento de estoque',
                'verbose_name_plural': 'Tipos de movimentos de estoque',
                'db_table': 'fo2_est_tipo_mov',
            },
        ),
    ]
