# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-18 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_est_tipo_mov'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipomovstq',
            name='codigo',
            field=models.CharField(default='-', max_length=100, unique=True, verbose_name='Código'),
        ),
    ]
