# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-19 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_tipomovstq_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('can_transferencia', 'Pode fazer transferência entre depósitos'),),
                'managed': False,
            },
        ),
    ]
