# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-27 17:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estoque', '0004_estoquepermissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocMovStq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=0, verbose_name='Número de documento')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('data', models.DateField()),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'Documento de movimento de estoque',
                'verbose_name_plural': 'Documentos de movimentos de estoque',
                'db_table': 'fo2_est_doc_mov',
            },
        ),
    ]
