# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-30 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_docmovstq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docmovstq',
            name='numero',
        ),
    ]
