# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-31 18:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0007_docmovstq_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docmovstq',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
    ]
