# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-31 18:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0027_produto_nivel_validate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estoque', '0008_docmovstq_usuario_on_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovStq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=0)),
                ('deposito_origem', models.IntegerField(verbose_name='Depósito de origem')),
                ('deposito_destino', models.IntegerField(verbose_name='Depósito de destino')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.DocMovStq', verbose_name='Documento de movimento de estoque')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produto.ProdutoItem')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'Movimento de estoque',
                'verbose_name_plural': 'Movimentos de estoque',
                'db_table': 'fo2_est_mov',
            },
        ),
    ]
