# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-03 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0009_movstq'),
    ]

    operations = [
        migrations.AddField(
            model_name='movstq',
            name='tipo_mov',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='estoque.TipoMovStq', verbose_name='Tipo de movimento'),
        ),
    ]
