# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-03 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def set_my_defaults(apps, schema_editor):
    MovStq = apps.get_model('estoque', 'MovStq')
    TipoMovStq = apps.get_model('estoque', 'TipoMovStq')
    for mov_stq in MovStq.objects.all().iterator():
        try:
            tipo_mov = TipoMovStq.objects.get(codigo='transf')
        except TipoMovStq.DoesNotExist:
            continue
        mov_stq.tipo_mov = tipo_mov
        mov_stq.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0010_movstq_tipo_mov'),
    ]

    operations = [
        migrations.RunPython(set_my_defaults, reverse_func),
    ]
