# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-03 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0013_movstq_tipo_mov_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipomovstq',
            name='menu',
            field=models.BooleanField(default=False, verbose_name='Aparece no menu'),
        ),
    ]
