# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-03 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0015_tipomovstq_ordem'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipomovstq',
            name='renomeia',
            field=models.BooleanField(default=False, verbose_name='Renomeia referência, cor ou tamanho'),
        ),
    ]
