# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-03 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0027_produto_nivel_validate'),
        ('estoque', '0017_tipomovstq_renomeia_alter'),
    ]

    operations = [
        migrations.AddField(
            model_name='movstq',
            name='novo_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movstqdest', to='produto.ProdutoItem'),
        ),
    ]
