# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-07 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0018_movstq_novo_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='movstq',
            name='hora',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
