# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-07 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0019_movstq_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movstq',
            name='hora',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
