# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-07 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0020_movstq_hora_set_on_insert'),
    ]

    operations = [
        migrations.AddField(
            model_name='movstq',
            name='obs',
            field=models.CharField(default='', max_length=100, verbose_name='Observação'),
        ),
    ]
