# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-12-14 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0022_estoque_permissions_verbose'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipomovstq',
            name='unidade',
            field=models.CharField(choices=[('1', '1 para 1'), ('M', 'Monta Kit'), ('D', 'Desmonta Kit')], default='1', max_length=1),
        ),
    ]
