# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-12-14 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0023_tipomovstq_unidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='movstq',
            name='itens_extras',
            field=models.CharField(default='', max_length=200),
        ),
    ]
