# Generated by Django 2.1.15 on 2022-03-30 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0024_movstq_itens_extras'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estoquepermissions',
            options={'managed': False, 'permissions': (('can_transferencia', 'Pode fazer transferência entre depósitos'), ('pode_zerar_depositos', 'Pode zerar depósitos')), 'verbose_name': 'Permissões de estoque'},
        ),
    ]
