# Generated by Django 3.0.14 on 2022-10-11 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0025_permissions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MetaPermissions',
        ),
    ]
