# Generated by Django 2.1.15 on 2022-03-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CdPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Permissões do CD',
                'permissions': (('can_admin_pallet', 'Pode administrar paletes'),),
                'managed': False,
            },
        ),
    ]
