# Generated by Django 2.1.15 on 2022-04-13 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cd', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cdpermissions',
            options={'managed': False, 'permissions': (('can_admin_pallet', 'Pode administrar paletes'), ('can_view_grades_estoque', 'Pode visualizar grades do estoque')), 'verbose_name': 'Permissões do CD'},
        ),
    ]
