# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-26 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='código')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('setor', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='e-mail')),
                ('tipo_num_1', models.CharField(blank=True, max_length=20, null=True, verbose_name='tipo do número 1')),
                ('num_1', models.CharField(blank=True, max_length=20, null=True, verbose_name='número 1')),
                ('tipo_num_2', models.CharField(blank=True, max_length=20, null=True, verbose_name='tipo do número 2')),
                ('num_2', models.CharField(blank=True, max_length=20, null=True, verbose_name='número 2')),
                ('dir_servidor', models.CharField(blank=True, max_length=200, null=True, verbose_name='diretório no servidor')),
                ('dir_local', models.CharField(blank=True, max_length=200, null=True, verbose_name='diretório no local')),
                ('create_at', models.DateTimeField(blank=True, null=True, verbose_name='Criada em')),
                ('update_at', models.DateTimeField(blank=True, null=True, verbose_name='alterado em')),
            ],
            options={
                'verbose_name': 'Conta',
                'db_table': 'fo2_emsign_account',
            },
        ),
    ]
