# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-07 21:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('remote_files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='e-mail')),
                ('nome', models.CharField(max_length=100)),
                ('setor', models.CharField(blank=True, max_length=100, null=True)),
                ('ddd_1', models.IntegerField(default=21, verbose_name='DDD 1')),
                ('num_1', models.CharField(blank=True, max_length=20, null=True, verbose_name='número 1')),
                ('ddd_2', models.IntegerField(default=21, verbose_name='DDD 2')),
                ('num_2', models.CharField(blank=True, max_length=20, null=True, verbose_name='número 2')),
                ('subdiretorio', models.CharField(max_length=200, verbose_name='sub-diretório de assinatura')),
                ('create_at', models.DateTimeField(blank=True, null=True, verbose_name='Criada em')),
                ('update_at', models.DateTimeField(blank=True, null=True, verbose_name='alterado em')),
                ('diretorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='remote_files.Diretorio')),
            ],
            options={
                'verbose_name': 'Conta',
                'db_table': 'fo2_emsign_account',
                'permissions': (('can_edit_mail_signature', 'Can edit mail signature'),),
            },
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64)),
                ('slug', models.SlugField()),
                ('template', models.CharField(max_length=64)),
                ('habilitado', models.NullBooleanField(default=False)),
            ],
            options={
                'db_table': 'fo2_emsign_layout',
            },
        ),
    ]
