# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-28 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_signature', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'permissions': (('can_edit_mail_signature', 'Can edit mail signature'),), 'verbose_name': 'Conta'},
        ),
    ]
