# Generated by Django 2.1.15 on 2021-10-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_signature', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='tipo',
            field=models.CharField(choices=[('tussor', 'Tussor'), ('agator', 'Agator')], default='tussor', max_length=10),
        ),
    ]
