# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-05 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_signature', '0002_account_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64)),
                ('slug', models.SlugField()),
                ('template', models.CharField(max_length=64)),
                ('habilitado', models.NullBooleanField(default=False)),
            ],
            options={
                'db_table': 'fo2_emsign_layout',
            },
        ),
    ]
