# Generated by Django 2.1.15 on 2021-10-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_signature', '0003_account_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='generate_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Gerada em'),
        ),
    ]
