# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-05 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_signature', '0003_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='arquivo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
