# Generated by Django 3.0.14 on 2022-10-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_signature', '0004_account_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layout',
            name='habilitado',
            field=models.BooleanField(default=False),
        ),
    ]
