# Generated by Django 3.2.16 on 2022-12-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_signature', '0005_email_signature_habilitado'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cnpj',
            field=models.BooleanField(default=False, verbose_name='Apresenta CNPJ'),
        ),
    ]
