# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-06 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_signature', '0006_account_remove_dir_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True, verbose_name='e-mail'),
        ),
    ]
