# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-07 00:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_signature', '0008_remove_account_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='arquivo',
        ),
    ]
