# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-07 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_signature', '0009_remove_account_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='ddd_1',
            field=models.IntegerField(default=21, verbose_name='DDD 1'),
        ),
        migrations.AddField(
            model_name='account',
            name='ddd_2',
            field=models.IntegerField(default=21, verbose_name='DDD 2'),
        ),
    ]
