# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-07 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_signature', '0010_account_add_ddd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='dir_servidor',
        ),
        migrations.AddField(
            model_name='account',
            name='subdiretorio',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='sub-diretório de assinatura'),
        ),
    ]
