# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-07 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remote_files', '0006_sevidor_wrong_type'),
        ('email_signature', '0011_account_subdiretorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='diretorio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='remote_files.Diretorio'),
            preserve_default=False,
        ),
    ]
