# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-07 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diretorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='descrição')),
                ('caminho', models.CharField(max_length=300)),
                ('file_perm', models.IntegerField(verbose_name='permissões (octal)')),
                ('file_user', models.CharField(max_length=50, verbose_name='usuário')),
                ('file_group', models.CharField(max_length=50, verbose_name='grupo')),
            ],
            options={
                'verbose_name': 'Diretório',
                'db_table': 'fo2_rfile_folder',
            },
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, unique=True, verbose_name='descrição')),
                ('hostname', models.CharField(max_length=50, unique=True)),
                ('ip4', models.CharField(max_length=15, unique=True)),
                ('port', models.IntegerField(default=22, verbose_name='porta ssh')),
                ('user', models.CharField(default=None, max_length=50, verbose_name='usuário')),
                ('key_file', models.FileField(blank=True, null=True, upload_to='upload/remote_files/servidor', verbose_name='Chave pública')),
            ],
            options={
                'verbose_name': 'Servidor',
                'verbose_name_plural': 'Servidores',
                'db_table': 'fo2_rfile_servidor',
            },
        ),
        migrations.AddField(
            model_name='diretorio',
            name='servidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='remote_files.Servidor'),
        ),
    ]
