# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-07 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, unique=True, verbose_name='descrição')),
                ('hostname', models.CharField(max_length=50, unique=True)),
                ('ip4', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'verbose_name': 'Servidor',
                'verbose_name_plural': 'Servidores',
                'db_table': 'fo2_rfile_servidor',
            },
        ),
    ]
