# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-07 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remote_files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diretorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='descrição')),
                ('caminho', models.CharField(max_length=300)),
                ('file_perm', models.IntegerField(verbose_name='permissões (octal)')),
                ('file_usuer', models.CharField(max_length=50, verbose_name='usuário')),
                ('file_group', models.CharField(max_length=50, verbose_name='grupo')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='remote_files.Servidor')),
            ],
            options={
                'verbose_name': 'Diretório',
                'db_table': 'fo2_rfile_folder',
            },
        ),
    ]
