# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-07 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_files', '0003_diretorio_field_rename'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='key_file',
            field=models.ImageField(blank=True, null=True, upload_to='upload/remote_files/servidor', verbose_name='Chave pública'),
        ),
    ]
