# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-07 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_files', '0004_servidor_key_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='user',
            field=models.CharField(default=None, max_length=50, verbose_name='usuário'),
        ),
    ]
