# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-07 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_files', '0006_sevidor_wrong_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='port',
            field=models.IntegerField(default=22, verbose_name='porta ssh'),
        ),
    ]
