# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-12-22 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEquipamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nome')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Tipo de equipamento',
                'verbose_name_plural': 'Tipos de equipamentos',
                'db_table': 'fo2_ti_tipo_equipamento',
            },
        ),
    ]
