# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-12-22 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('slug', models.SlugField()),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ti.TipoEquipamento')),
            ],
            options={
                'db_table': 'fo2_ti_equipamento',
            },
        ),
    ]
