# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-12-22 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0004_tipointerface'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('slug', models.SlugField()),
                ('mac_adress', models.CharField(blank=True, max_length=17, null=True, verbose_name='Endereço MAC')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ti.TipoInterface')),
            ],
            options={
                'db_table': 'fo2_ti_interface',
            },
        ),
    ]
