# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-12-22 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0005_interface'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipamento',
            old_name='tipo',
            new_name='type',
        ),
    ]
