# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-12-22 19:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0009_fo2_ti_equipment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Equipamento',
            new_name='Equipment',
        ),
    ]
