# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-12-22 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0010_equipment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='ip_principal',
            new_name='primary_ip',
        ),
    ]
