# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-12-22 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0014_equipment_meta'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tipointerface',
            table='fo2_ti_interface_type',
        ),
    ]
