# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-12-22 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0015_fo2_ti_interface_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TipoInterface',
            new_name='InterfaceType',
        ),
    ]
