# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-12-22 20:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0018_equipment_interface'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interface',
            old_name='ip',
            new_name='fixed_ip',
        ),
    ]
