# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-12-23 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0022_interface_equipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentinterface',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='equipmentinterface',
            name='interface',
        ),
        migrations.DeleteModel(
            name='EquipmentInterface',
        ),
    ]
