# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-12-29 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0023_del_equipmentinterface'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='dhcp_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ti.DhcpConfig', verbose_name='Configuração de DHCP'),
        ),
    ]
