# Generated by Django 2.1.15 on 2021-09-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0026_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='descr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição'),
        ),
    ]
