# Generated by Django 2.1.15 on 2021-09-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0028_equipment_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Nome-chave'),
        ),
    ]
