# Generated by Django 2.1.15 on 2021-09-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0029_equipment_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='OSType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nome')),
                ('slug', models.SlugField(unique=True, verbose_name='Nome-chave')),
            ],
            options={
                'verbose_name': 'Tipo de SO',
                'verbose_name_plural': 'Tipos de SO',
                'db_table': 'fo2_ti_os_type',
            },
        ),
    ]
