# Generated by Django 2.1.15 on 2021-09-29 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0031_equipment_use'),
    ]

    operations = [
        migrations.CreateModel(
            name='OS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nome')),
                ('version', models.CharField(max_length=60, verbose_name='Versão')),
                ('bits', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(unique=True, verbose_name='Nome-chave')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ti.OSType', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'SO',
                'verbose_name_plural': 'SO',
                'db_table': 'fo2_ti_os',
            },
        ),
    ]
