# Generated by Django 2.1.15 on 2021-09-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0032_os'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nome')),
                ('slug', models.SlugField(unique=True, verbose_name='Nome-chave')),
            ],
            options={
                'verbose_name': 'Empresa',
                'db_table': 'fo2_ti_empresa',
            },
        ),
    ]
