# Generated by Django 2.1.15 on 2021-09-29 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0033_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nome')),
                ('slug', models.SlugField(unique=True, verbose_name='Nome-chave')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ti.Empresa')),
            ],
            options={
                'verbose_name': 'Local em empresa',
                'db_table': 'fo2_ti_local',
            },
        ),
    ]
