# Generated by Django 2.1.15 on 2021-09-29 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0034_local'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Local',
            new_name='Location',
        ),
    ]
