# Generated by Django 2.1.15 on 2021-09-30 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0036_location'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='empresa',
            table='fo2_it_company',
        ),
    ]
