# Generated by Django 2.1.15 on 2021-09-30 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0037_it_company'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Empresa',
            new_name='Company',
        ),
    ]
