# Generated by Django 2.1.15 on 2021-09-30 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0038_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dhcpconfig',
            name='primary_equipment',
        ),
        migrations.RemoveField(
            model_name='dhcpconfig',
            name='secondary_equipment',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='type',
        ),
        migrations.RemoveField(
            model_name='interface',
            name='dhcp_config',
        ),
        migrations.RemoveField(
            model_name='interface',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='interface',
            name='type',
        ),
        migrations.RemoveField(
            model_name='location',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='os',
            name='type',
        ),
        migrations.RemoveField(
            model_name='share',
            name='equipment',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='DhcpConfig',
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
        migrations.DeleteModel(
            name='EquipmentType',
        ),
        migrations.DeleteModel(
            name='Interface',
        ),
        migrations.DeleteModel(
            name='InterfaceType',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='OS',
        ),
        migrations.DeleteModel(
            name='OSType',
        ),
        migrations.DeleteModel(
            name='Share',
        ),
    ]
