# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-06 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SugestaoCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(db_index=True, max_length=1, verbose_name='Nível')),
                ('referencia', models.CharField(db_index=True, max_length=5, verbose_name='Referência')),
                ('tamanho', models.CharField(db_index=True, max_length=3, verbose_name='Tamanho')),
                ('ordem_tamanho', models.IntegerField(db_index=True, default=0, verbose_name='ordem tamanho')),
                ('cor', models.CharField(db_index=True, max_length=6, verbose_name='Cor')),
                ('data', models.DateTimeField(db_index=True, verbose_name='Data do calculo')),
            ],
            options={
                'verbose_name': 'Sugestão de compra',
                'db_table': 'fo2_sugestao_compra',
            },
        ),
        migrations.CreateModel(
            name='SugestaoCompraDatas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_compra', models.DateField(db_index=True, verbose_name='Data de compra')),
                ('data_recepcao', models.DateField(verbose_name='Data de recepção')),
                ('qtd', models.DecimalField(decimal_places=3, max_digits=13, verbose_name='Quantidade')),
                ('sugestao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insumo.SugestaoCompra', verbose_name='Sugestão de compra')),
            ],
            options={
                'verbose_name': 'Datas da sugestão de compra',
                'db_table': 'fo2_sugestao_compra_datas',
            },
        ),
    ]
