# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-07 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sugestaocompra',
            name='create_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Criada em'),
        ),
    ]
