# Generated by Django 2.1.15 on 2022-05-10 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0002_sugestaocompra_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sugestaocompradatas',
            name='sugestao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insumo.SugestaoCompra', verbose_name='Sugestão de compra'),
        ),
    ]
