# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notafiscal',
            options={'verbose_name': 'Nota Fiscal', 'verbose_name_plural': 'Notas Fiscais'},
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='faturamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='entrega',
            field=models.DateField(blank=True, null=True, verbose_name='entrega/agendamento'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='numero',
            field=models.IntegerField(unique=True, verbose_name='número'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='observação'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='saida',
            field=models.DateField(blank=True, null=True, verbose_name='saída'),
        ),
    ]
