# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0002_auto_20170707_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='cod_status',
            field=models.IntegerField(blank=True, null=True, verbose_name='status (cód.)'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='msg_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='status (descr.)'),
        ),
    ]
