# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0003_auto_20170710_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='dest_cnpj',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='dest_nome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Destinatário'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='natu_venda',
            field=models.BooleanField(default=False, verbose_name='venda'),
        ),
    ]
