# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0004_auto_20170711_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='natu_descr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='natureza'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF'),
        ),
    ]
