# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0005_auto_20170711_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='transp_nome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='transportadora'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='cod_status',
            field=models.IntegerField(blank=True, null=True, verbose_name='status'),
        ),
    ]
