# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-04 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0009_auto_20180118_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notafiscal',
            name='numero',
            field=models.IntegerField(db_index=True, unique=True, verbose_name='número'),
        ),
    ]
