# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-04 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0010_auto_20180904_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='trail',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32, null=True),
        ),
    ]
