# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-25 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0012_notafiscal_nf_devolucao'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosicaoCarga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Posição de carga(NF)',
                'verbose_name_plural': 'Posições de carga(NF)',
                'db_table': 'fo2_pos_carga',
            },
        ),
    ]
