# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-25 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0014_posicaocarga_loaddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='RotinaLogistica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=30, unique=True)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Rotina ligada à app Logistica',
                'verbose_name_plural': 'Rotinas ligadas à app Logistica',
                'db_table': 'fo2_logist_rotina',
            },
        ),
    ]
