# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-25 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0019_notafiscal_posicao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notafiscal',
            options={'permissions': (('can_beep_shipment', 'Can beep shipment'),), 'verbose_name': 'Nota Fiscal', 'verbose_name_plural': 'Notas Fiscais'},
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='posicao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='logistica.PosicaoCarga', verbose_name='Posição'),
        ),
    ]
