# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-26 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0020_notafiscal_can_beep_shipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosicaoCargaAlteracaoLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(db_index=True, verbose_name='número')),
                ('time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Hora')),
                ('user', models.CharField(db_index=True, max_length=64, verbose_name='Usuário')),
                ('saida', models.DateField(blank=True, null=True, verbose_name='saída')),
                ('final', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='log_posicao_final_set', to='logistica.PosicaoCarga', verbose_name='Estado Final')),
                ('inicial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='log_posicao_inicial_set', to='logistica.PosicaoCarga', verbose_name='Estado inicial')),
            ],
            options={
                'verbose_name': 'Log de alteração de posição de carga(NF)',
                'db_table': 'fo2_pos_carga_alt_log',
            },
        ),
    ]
