# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-04-11 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0023_notafiscal_acerta_posicao_entregue'),
    ]

    operations = [
        migrations.AddField(
            model_name='posicaocargaalteracao',
            name='so_nfs_ativas',
            field=models.BooleanField(default=True, verbose_name='Só NFs ativas'),
        ),
    ]
