# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-05-10 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0026_0026_fo2_fat_nf__ativa__index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notafiscal',
            name='faturamento',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
