# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-08 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0027_0027_fo2_fat_nf__faturamento__index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notafiscal',
            name='msg_status',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='status (descr.)'),
        ),
    ]
