# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-14 17:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistica', '0028_fo2_fat_nf_msg'),
    ]

    operations = [
        migrations.CreateModel(
            name='NfEntrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emissor', models.CharField(max_length=200)),
                ('numero', models.IntegerField(db_index=True, verbose_name='número')),
                ('descricao', models.CharField(max_length=200, verbose_name='descrição')),
                ('qtd', models.DecimalField(decimal_places=4, max_digits=13, verbose_name='Quantidade')),
                ('hora_entrada', models.TimeField(auto_now_add=True, null=True, verbose_name='hora de entrada')),
                ('transportadora', models.CharField(max_length=100)),
                ('motorista', models.CharField(max_length=100)),
                ('placa', models.CharField(max_length=10)),
                ('responsavel', models.CharField(max_length=100, verbose_name='responsável')),
                ('quando', models.DateTimeField(auto_now_add=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'Nota fiscal de entrada',
                'verbose_name_plural': 'Notas fiscais de entrada',
                'db_table': 'fo2_nf_entrada',
            },
        ),
    ]
