# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-14 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0029_nfentrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfentrada',
            name='hora_entrada',
            field=models.TimeField(null=True, verbose_name='hora de entrada'),
        ),
    ]
