# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-14 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0030_nfentrada_hora_entrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfentrada',
            name='numero',
            field=models.IntegerField(verbose_name='número'),
        ),
    ]
