# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-14 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0032_nfentrada_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfentrada',
            name='hora_entrada',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='hora de entrada'),
        ),
    ]
