# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-14 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0033_nfentrada_hora_entrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfentrada',
            name='cadastro',
            field=models.CharField(default='', max_length=20, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='nfentrada',
            name='qtd',
            field=models.DecimalField(decimal_places=4, max_digits=13, verbose_name='quantidade'),
        ),
    ]
