# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-15 22:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0034_nfentrada_verbose_names'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nfentrada',
            unique_together=set([('cadastro', 'numero')]),
        ),
    ]
