# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-17 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0035_nfentrada_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfentrada',
            name='quando',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
