# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-17 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import logistica.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_empresa_numero_unique'),
        ('logistica', '0036_nfentrada_quando'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfentrada',
            name='empresa',
            field=models.ForeignKey(default=logistica.models.NfEntrada.get_tussor, on_delete=django.db.models.deletion.PROTECT, to='base.Empresa'),
        ),
    ]
