# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-17 23:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0037_nfentrada_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='NfEntradaAgator',
            fields=[
            ],
            options={
                'verbose_name': 'Nota fiscal de entrada Agator',
                'verbose_name_plural': 'Notas fiscais de entrada Agator',
                'proxy': True,
                'indexes': [],
            },
            bases=('logistica.nfentrada',),
        ),
        migrations.CreateModel(
            name='NfEntradaTussor',
            fields=[
            ],
            options={
                'verbose_name': 'Nota fiscal de entrada Tussor',
                'verbose_name_plural': 'Notas fiscais de entrada Tussor',
                'proxy': True,
                'indexes': [],
            },
            bases=('logistica.nfentrada',),
        ),
    ]
