# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-18 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0038_nfentradaagator_nfentradatussor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfentrada',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Empresa'),
        ),
    ]
