# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-23 17:13
from __future__ import unicode_literals

from datetime import datetime

from django.db import migrations, models
import django.utils.timezone


def migrate_init_chegada(apps, schema_editor):

    NfEntrada = apps.get_model('logistica', 'NfEntrada')

    for mm in NfEntrada.objects.all():
        mm.chegada = datetime.combine(mm.quando.date(), mm.hora_entrada)
        mm.save()


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0039_nfentrada_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfentrada',
            name='chegada',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='chegada'),
        ),
        migrations.RunPython(migrate_init_chegada, migrations.RunPython.noop),
    ]
