# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-23 18:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0040_nfentrada_chegada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nfentrada',
            name='hora_entrada',
        ),
    ]
