# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-24 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0041_remove_nfentrada_hora_entrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfentrada',
            name='qtd',
            field=models.IntegerField(verbose_name='quantidade'),
        ),
    ]
