# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-24 10:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0042_nfentrada_qtd_integer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nfentrada',
            old_name='qtd',
            new_name='volumes',
        ),
    ]
