# Generated by Django 2.1.15 on 2021-09-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0045_nfentrada_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfentrada',
            name='tipo',
            field=models.CharField(choices=[('s', 'Serviço'), ('v', 'Venda'), ('_', '')], default='_', max_length=1),
        ),
    ]
