# Generated by Django 2.1.15 on 2021-09-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0046_nfentrada_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfentrada',
            name='tipo',
            field=models.CharField(choices=[('s', 'Serviço'), ('v', 'Venda'), ('_', '')], default='v', max_length=1),
        ),
    ]
