# Generated by Django 2.1.15 on 2021-09-13 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0047_nfentrada_tipo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nfentrada',
            unique_together={('cadastro', 'numero', 'tipo')},
        ),
    ]
