# Generated by Django 3.2.16 on 2023-07-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0052_notafiscal_acerta_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notafiscal',
            name='trail',
            field=models.CharField(blank=True, db_index=True, default='', max_length=33, null=True),
        ),
    ]
