# Generated by Django 3.2.16 on 2023-07-24 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0055_alter_notafiscal_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='data_base',
            field=models.DateField(db_index=True, default=datetime.date(2000, 1, 1)),
        ),
    ]
