# Generated by Django 3.2.16 on 2023-07-24 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0056_notafiscal_data_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notafiscal',
            name='data_base',
            field=models.DateField(db_index=True, default=datetime.date(2001, 1, 2), verbose_name='Data base'),
        ),
    ]
