# Generated by Django 3.2.16 on 2023-07-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0057_alter_notafiscal_data_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notafiscal',
            name='empresa',
            field=models.SmallIntegerField(choices=[(1, 'Tussor'), (2, 'Agator'), (3, 'Corte'), (4, 'Gavi')], db_index=True, default=1),
        ),
    ]
