# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-10 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipeAtendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=20)),
                ('slug', models.SlugField()),
                ('descricao', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Equipe de atendimento',
                'verbose_name_plural': 'Equipes de atendimento',
                'db_table': 'fo2_serv_equipe',
            },
        ),
    ]
