# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-10 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoFuncaoExercida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=20)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Tipo de função exercida',
                'verbose_name_plural': 'Tipos de função exercida',
                'db_table': 'fo2_serv_tp_funcao_exer',
            },
        ),
    ]
