# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-10 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0002_tipofuncaoexercida'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipofuncaoexercida',
            name='nivel_operacional',
            field=models.IntegerField(default=0, verbose_name='Nível operacional'),
        ),
    ]
