# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-10 01:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servico', '0003_tipofuncaoexercida_nivel_operacional'),
    ]

    operations = [
        migrations.CreateModel(
            name='PapelUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='servico.EquipeAtendimento')),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servico.TipoFuncaoExercida', verbose_name='função')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'Papel de usuário',
                'verbose_name_plural': 'Papeis de usuário',
                'db_table': 'fo2_serv_papel_usuario',
            },
        ),
    ]
