# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-10 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0004_papelusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelAtendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=20)),
                ('slug', models.SlugField()),
                ('horas', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Nível de atendimento',
                'verbose_name_plural': 'Níveis de atendimento',
                'db_table': 'fo2_serv_nivel_atend',
            },
        ),
    ]
