# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-12 18:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servico', '0008_tipodocumento_loaddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumeroDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(blank=True, null=True, verbose_name='criado em')),
                ('ativo', models.BooleanField(default=False)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servico.TipoDocumento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'Número de documento',
                'verbose_name_plural': 'Números de documento',
                'db_table': 'fo2_serv_num_doc',
            },
        ),
    ]
