# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-12 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0010_tipoevento'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoevento',
            name='ordem',
            field=models.IntegerField(default=0),
        ),
    ]
