# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-12 19:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servico', '0012_tipoevento_loaddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicoEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(blank=True, null=True, verbose_name='Criado em')),
                ('descricao', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Descrição')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servico.EquipeAtendimento', verbose_name='Equipe de atendimento')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servico.TipoEvento')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servico.NivelAtendimento', verbose_name='Nível de etendimento')),
                ('numero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servico.NumeroDocumento', verbose_name='Número')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Evento relacionado a serviços',
                'verbose_name_plural': 'Eventos relacionados a serviços',
                'db_table': 'fo2_serv_servico_evento',
            },
        ),
    ]
