# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-12 19:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0013_servicoevento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numerodocumento',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
    ]
