# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-12 20:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0014_numerodocumentoauto_user_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicoevento',
            name='descricao',
            field=models.CharField(default='', max_length=2000, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='servicoevento',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servico.NivelAtendimento', verbose_name='Nível de atendimento'),
        ),
        migrations.AlterField(
            model_name='servicoevento',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
