# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-20 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0017_tipoevento_loaddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoevento',
            name='ativar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tipoevento',
            name='criar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tipoevento',
            name='edita_descricao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tipoevento',
            name='edita_equipe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tipoevento',
            name='edita_nivel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tipoevento',
            name='inativar',
            field=models.BooleanField(default=False),
        ),
    ]
