# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-21 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0021_statusdocumento_loaddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='numerodocumento',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='servico.StatusDocumento'),
        ),
    ]
