# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-21 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0022_numerodocumento_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoDeStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servico.TipoEvento')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servico.StatusDocumento')),
            ],
            options={
                'verbose_name': 'Evento de status',
                'verbose_name_plural': 'Eventos de status',
                'db_table': 'fo2_serv_sevento_status',
            },
        ),
    ]
