# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-21 17:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0023_eventodestatus'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='eventodestatus',
            table='fo2_serv_evento_status',
        ),
    ]
