# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-21 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0024_eventodestatus_table_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventodestatus',
            name='status',
        ),
        migrations.AddField(
            model_name='eventodestatus',
            name='status_pos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_criadores', to='servico.StatusDocumento'),
        ),
        migrations.AddField(
            model_name='eventodestatus',
            name='status_pre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_dependentes', to='servico.StatusDocumento'),
        ),
    ]
