# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-21 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0025_eventodestatus_status_pre_pos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numerodocumento',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servico.StatusDocumento'),
        ),
    ]
