# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-21 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0026_numerodocumento_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusdocumento',
            name='cancelado',
        ),
        migrations.RemoveField(
            model_name='statusdocumento',
            name='criado',
        ),
        migrations.RemoveField(
            model_name='statusdocumento',
            name='iniciado',
        ),
        migrations.RemoveField(
            model_name='statusdocumento',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='statusdocumento',
            name='terminado',
        ),
        migrations.AddField(
            model_name='statusdocumento',
            name='codigo',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
