# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-21 18:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0027_statusdocumento_reestruturado'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StatusDocumento',
            new_name='Status',
        ),
    ]
