# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-21 18:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0028_statusdocumento_vira_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status', 'verbose_name_plural': 'Status'},
        ),
        migrations.AlterModelTable(
            name='status',
            table='fo2_serv_status',
        ),
    ]
