# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-21 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0032_evento_table_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='slug',
            new_name='codigo',
        ),
    ]
