# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-21 19:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0034_evento_codigo_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='ativar',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='criar',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='inativar',
        ),
    ]
