# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-21 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0037_eventodestatus_to_statusevento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statusevento',
            options={'verbose_name': 'Status-Evento', 'verbose_name_plural': 'Status-Evento'},
        ),
        migrations.AlterModelTable(
            name='statusevento',
            table='fo2_serv_status_evento',
        ),
    ]
