# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-23 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0039_eventodestatus_init'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NumeroDocumento',
            new_name='Documento',
        ),
    ]
