# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-23 21:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0040_numeronocumento_to_documento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'verbose_name': 'Documento'},
        ),
        migrations.AlterModelTable(
            name='documento',
            table='fo2_serv_doc',
        ),
    ]
