# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-23 21:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0041_documento_table_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicoevento',
            old_name='numero',
            new_name='documento',
        ),
    ]
