# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-23 21:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0043_servicoevento_documento'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServicoEvento',
            new_name='Interacao',
        ),
    ]
