# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-23 21:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0044_servicoevento_to_interacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interacao',
            options={'verbose_name': 'Interação em documento', 'verbose_name_plural': 'Interações em documentos'},
        ),
        migrations.AlterModelTable(
            name='interacao',
            table='fo2_serv_interacao',
        ),
    ]
