# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-27 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0045_interacao_table_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='interacao',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='servico.Status'),
        ),
    ]
