# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-27 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0046_interacao_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='status',
        ),
    ]
