# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-30 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0048_statusevento_insere'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipofuncaoexercida',
            name='parte',
            field=models.BooleanField(default=True),
        ),
    ]
