# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-30 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0049_tipofuncaoexercida_parte'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TipoFuncaoExercida',
            new_name='FuncaoExercida',
        ),
        migrations.AlterModelOptions(
            name='funcaoexercida',
            options={'verbose_name': 'Função exercida', 'verbose_name_plural': 'Funções exercidas'},
        ),
    ]
