# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-30 17:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0050_tipofuncaoexercida_funcaoexercida'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='funcaoexercida',
            table='fo2_serv_funcao_exercida',
        ),
    ]
