# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-30 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0051_funcaoexercida_table_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statusevento',
            options={'verbose_name': 'Status-Evento', 'verbose_name_plural': 'Status-Eventos'},
        ),
    ]
