# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-30 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0052_statusevento_verbose_name_plural'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PapelUsuario',
            new_name='UsuarioFuncao',
        ),
        migrations.AlterModelOptions(
            name='usuariofuncao',
            options={'verbose_name': 'Usuário-função', 'verbose_name_plural': 'Usuários-funções'},
        ),
    ]
