# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-30 17:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0053_papelusuario_usuariofuncao'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuariofuncao',
            table='fo2_serv_usuario_funcao',
        ),
    ]
