# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-05 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0057_statusevento_insere'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NivelAtendimento',
            new_name='Classificacao',
        ),
    ]
