# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-05 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0058_nivelatendimento_classificacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classificacao',
            options={'verbose_name': 'Classificação', 'verbose_name_plural': 'Classificações'},
        ),
        migrations.AlterModelTable(
            name='classificacao',
            table='fo2_serv_classificacao',
        ),
    ]
