# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-05 16:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0059_classificacao_table_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interacao',
            old_name='nivel',
            new_name='classificacao',
        ),
    ]
