# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-05 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0060_interacao_nivel_classificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interacao',
            name='classificacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servico.Classificacao', verbose_name='Classificação'),
        ),
    ]
