# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-05 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0061_Interacao_classificacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='edita_nivel',
            new_name='edita_classificacao',
        ),
    ]
