# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-05 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0062_evento_edita_classificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='codigo',
            field=models.CharField(max_length=20, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='edita_classificacao',
            field=models.BooleanField(default=False, verbose_name='Edita classificação'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='edita_descricao',
            field=models.BooleanField(default=False, verbose_name='Edita descrição'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='edita_equipe',
            field=models.BooleanField(default=False, verbose_name='Edita equipe'),
        ),
    ]
