# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-05 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0063_evento_fields_verbose_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='nivel_op_minimo',
            field=models.IntegerField(default=0, verbose_name='Nivel operacional mínimo'),
        ),
    ]
