# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-05 19:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0064_evento_nivel_op_minimo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcaoexercida',
            old_name='parte',
            new_name='independente',
        ),
    ]
