# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-12 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0068_statusevento_insere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='codigo',
            field=models.CharField(max_length=20, verbose_name='Código'),
        ),
    ]
