# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-12-22 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0002_equipamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='ip',
        ),
        migrations.AddField(
            model_name='equipamento',
            name='ip_principal',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Principal'),
        ),
    ]
