# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-12-22 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0003_equipamento_ip_principal'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoInterface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nome')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Tipo de interface',
                'verbose_name_plural': 'Tipos de interfaces',
                'db_table': 'fo2_ti_tipo_interface',
            },
        ),
    ]
