# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-12-22 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0006_equipamento_tipo_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ti.TipoEquipamento', verbose_name='Tipo'),
        ),
    ]
