# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-12-22 19:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0011_equip_primary_ip'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tipoequipamento',
            table='fo2_ti_equipment_type',
        ),
    ]
