# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-12-22 19:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0013_equipment_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': 'Equipamento'},
        ),
    ]
