# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-12-22 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0017_equipmentinterface'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentinterface',
            options={'verbose_name': 'Interface de equipamento', 'verbose_name_plural': 'Interfaces de equipamentos'},
        ),
        migrations.AlterField(
            model_name='equipmentinterface',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ti.Equipment', verbose_name='Equipamento'),
        ),
    ]
