# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-12-22 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0019_interface_fixed_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='DhcpConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('slug', models.SlugField()),
                ('primary_equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_dhcp', to='ti.Equipment', verbose_name='Equipamento primário')),
                ('secondary_equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secondary_dhcp', to='ti.Equipment', verbose_name='Equipamento secundário')),
            ],
            options={
                'verbose_name': 'Configuração DHCP',
                'verbose_name_plural': 'Configurações DHCP',
                'db_table': 'fo2_ti_dhcp_config',
            },
        ),
    ]
