# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-12-22 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0020_dhcpconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhcpconfig',
            name='secondary_equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secondary_dhcp', to='ti.Equipment', verbose_name='Equipamento secundário'),
        ),
    ]
