# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-12-23 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0021_secondary_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ti.Equipment', verbose_name='Equipamento'),
        ),
    ]
