# Generated by Django 2.1.15 on 2021-07-02 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0025_dhcp_config_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nome')),
                ('path', models.CharField(max_length=200, verbose_name='Caminho')),
                ('read_only', models.BooleanField(default=False, verbose_name='Somente leitura')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ti.Equipment', verbose_name='Servidor')),
            ],
            options={
                'verbose_name': 'Compartilhamento',
                'db_table': 'fo2_ti_share',
            },
        ),
    ]
