# Generated by Django 2.1.15 on 2021-09-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0027_equipment_descr'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='users',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuário(s)'),
        ),
    ]
