# Generated by Django 2.1.15 on 2021-09-29 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0035_location'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='location',
            table='fo2_ti_location',
        ),
    ]
