# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-04-29 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstoqueManual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True)),
                ('referencia', models.CharField(db_index=True, max_length=5, verbose_name='Referência')),
                ('tamanho', models.CharField(db_index=True, max_length=3)),
                ('cor', models.CharField(db_index=True, max_length=6)),
                ('qtd', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Estoque manual de produtos acabados',
                'db_table': 'fo2_estoque_manual',
            },
        ),
    ]
