# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-06-25 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloPassado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=50, unique=True)),
                ('padrao', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name': 'Modelo de análise do passado',
                'verbose_name_plural': 'Modelos de análise do passado',
                'db_table': 'fo2_mod_passado',
            },
        ),
    ]
