# -*- coding: utf-8 -*-
# Generated by Anselmo on 2019-06-25 12:42
from __future__ import unicode_literals

from django.db import migrations, models


def load_mod_passado_from_fixture(apps, schema_editor):
    from django.core.management import call_command
    call_command("loaddata", "0002_fo2_mod_passado_loaddata")


def delete_mod_passado(apps, schema_editor):
    ModeloPassado = apps.get_model("comercial", "ModeloPassado")
    ModeloPassado.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            load_mod_passado_from_fixture, delete_mod_passado),
    ]
