# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-06-26 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0002_fo2_mod_passado_loaddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloPassadoPeriodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField()),
                ('meses', models.IntegerField()),
                ('peso', models.IntegerField()),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial.ModeloPassado')),
            ],
            options={
                'verbose_name': 'Período de modelo de análise do passado',
                'verbose_name_plural': 'Períodos de modelo de análise do passado',
                'db_table': 'fo2_mod_pass_periodo',
            },
        ),
    ]
