# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-07-04 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0006_metaestoquecor'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaestoque',
            name='meta_estoque',
            field=models.IntegerField(default=0),
        ),
    ]
