# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-24 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0009_metaestoquetamanho_ordem'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaestoque',
            name='meta_giro',
            field=models.IntegerField(default=0),
        ),
    ]
