# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-10 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0010_metaestoque_meta_giro'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaFaturamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('faturamento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Meta de faturamento',
                'db_table': 'fo2_meta_faturamento',
                'permissions': (('can_define_revenues', 'Can define revenues'),),
            },
        ),
    ]
