# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-10 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0011_metafaturamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metafaturamento',
            name='faturamento',
            field=models.IntegerField(default=0),
        ),
    ]
