# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-11 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0012_metafaturamento_faturamento_integer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendenciaFaturamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField(verbose_name='mês')),
                ('ordem', models.IntegerField(default=1)),
                ('cliente', models.CharField(max_length=50)),
                ('pendencia', models.CharField(max_length=500, verbose_name='pendência')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('entrega', models.CharField(max_length=50)),
                ('responsavel', models.CharField(max_length=50, verbose_name='responsável')),
                ('obs', models.CharField(blank=True, max_length=50, null=True, verbose_name='observação')),
            ],
            options={
                'verbose_name': 'Pendência de faturamento',
                'db_table': 'fo2_pendencia_faturamento',
            },
        ),
    ]
