# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-09 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0013_pendenciafaturamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='metafaturamento',
            name='ativa',
            field=models.BooleanField(default=True),
        ),
    ]
