# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-09 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0015_metafaturamento_ajuste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metafaturamento',
            name='ativa',
        ),
    ]
