# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-23 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0016_remove_metafaturamento_ativa'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaModeloReferencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=5)),
                ('referencia', models.CharField(max_length=5, verbose_name='Referência')),
                ('incl_excl', models.CharField(max_length=1, verbose_name='Inclui/Exclui')),
            ],
            options={
                'verbose_name': 'Referência de modelo para meta',
                'verbose_name_plural': 'Referências de modelos para meta',
                'db_table': 'fo2_meta_mod_ref',
            },
        ),
    ]
