# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-23 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0017_metamodeloreferencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='metamodeloreferencia',
            name='multiplicador',
            field=models.IntegerField(default=1),
        ),
    ]
