# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-08 21:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0018_metamodeloreferencia_multiplicador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metamodeloreferencia',
            name='multiplicador',
        ),
    ]
