# Generated by Django 2.1.15 on 2021-08-31 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0019_remove_metamodeloreferencia_multiplicador'),
    ]

    operations = [
        migrations.AddField(
            model_name='metafaturamento',
            name='reparo',
            field=models.IntegerField(default=0),
        ),
    ]
