# Generated by Django 2.1.15 on 2022-04-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0020_metafaturamento_reparo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComercialPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Permissões do Comercial',
                'permissions': (('can_gerenciar_nf_especial', 'Pode gerenciar NF especial'),),
                'managed': False,
            },
        ),
    ]
