# Generated by Django 2.1.15 on 2022-05-10 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0021_comercialpermissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metaestoquecor',
            name='meta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comercial.MetaEstoque'),
        ),
        migrations.AlterField(
            model_name='metaestoquetamanho',
            name='meta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comercial.MetaEstoque'),
        ),
        migrations.AlterField(
            model_name='modelopassadoperiodo',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comercial.ModeloPassado'),
        ),
    ]
