# Generated by Django 2.1.15 on 2022-09-14 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0023_metamodeloreferencia_quantidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metamodeloreferencia',
            name='incl_excl',
        ),
    ]
