# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-23 18:57
from __future__ import unicode_literals

from django.db import migrations, models


def load_tipo_maquina_from_fixture(apps, schema_editor):
    from django.core.management import call_command
    call_command("loaddata", "0002_fo2_tipo_maquina_loaddata")


def delete_tipo_maquina(apps, schema_editor):
    TipoMaquina = apps.get_model("manutancao", "TipoMaquina")
    TipoMaquina.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            load_tipo_maquina_from_fixture, delete_tipo_maquina),
    ]
