# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-07-12 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0002_fo2_tipo_maquina_loaddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadeTempo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=1, verbose_name='Código')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Unidade de tempo',
                'verbose_name_plural': 'Unidades de tempo',
                'db_table': 'fo2_man_unidade_tempo',
            },
        ),
    ]
