# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-23 18:57
from __future__ import unicode_literals

from django.db import migrations, models


def load_man_unidade_tempo_from_fixture(apps, schema_editor):
    from django.core.management import call_command
    call_command("loaddata", "0004_fo2_man_unidade_tempo_loaddata")


def delete_man_unidade_tempo(apps, schema_editor):
    UnidadeTempo = apps.get_model("manutencao", "UnidadeTempo")
    UnidadeTempo.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0003_unidadetempo'),
    ]

    operations = [
        migrations.RunPython(
            load_man_unidade_tempo_from_fixture, delete_man_unidade_tempo),
    ]
