# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-07-12 19:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0006_0006_fo2_man_user_tipo_maq'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='data_inicio',
            field=models.DateField(default=datetime.date(2019, 7, 12), verbose_name='Data de início da rotina'),
            preserve_default=False,
        ),
    ]
