# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-07-12 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0009_fo2_man_atividade_loaddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadeMetrica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField(default=0)),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manutencao.Atividade')),
            ],
            options={
                'verbose_name': 'Metrica de atividade',
                'verbose_name_plural': 'Metricas de atividades',
                'db_table': 'fo2_man_atividade_metrica',
            },
        ),
    ]
