# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-07-12 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0011_fo2_man_atividade_metrica_loaddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rotina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_tempo', models.IntegerField(default=1, verbose_name='Quantidade de tempo')),
                ('nome', models.CharField(max_length=50)),
                ('tipo_maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manutencao.TipoMaquina', verbose_name='Tipo de máquina')),
                ('unidade_tempo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manutencao.UnidadeTempo', verbose_name='Unidade de tempo')),
            ],
            options={
                'verbose_name': 'Rotina de manutenção',
                'verbose_name_plural': 'Rotinas de manutenção',
                'db_table': 'fo2_man_rotina',
            },
        ),
    ]
