# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-23 18:57
from __future__ import unicode_literals

from django.db import migrations, models


def load_man_rotina_loaddata_from_fixture(apps, schema_editor):
    from django.core.management import call_command
    call_command("loaddata", "0013_fo2_man_rotina_loaddata")


def delete_man_rotina_loaddata(apps, schema_editor):
    Rotina = apps.get_model("manutencao", "Rotina")
    Rotina.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0012_rotina'),
    ]

    operations = [
        migrations.RunPython(
            load_man_rotina_loaddata_from_fixture,
            delete_man_rotina_loaddata),
    ]
