# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-07-12 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0013_fo2_man_rotina_loaddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='RotinaPasso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField(default=0)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manutencao.Atividade')),
                ('rotina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manutencao.Rotina')),
            ],
            options={
                'verbose_name': 'Passo de rotina',
                'verbose_name_plural': 'Passos de rotinas',
                'db_table': 'fo2_man_rotina_passo',
            },
        ),
    ]
