# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-07-15 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0015_fo2_man_rotina_passo_loaddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('qtd_tempo', models.IntegerField(default=1, verbose_name='Quantidade de tempo')),
                ('ordem', models.IntegerField(default=0)),
                ('unidade_tempo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manutencao.UnidadeTempo', verbose_name='Unidade de tempo')),
            ],
            options={
                'verbose_name': 'Período',
                'db_table': 'fo2_man_periodo',
            },
        ),
    ]
