# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-23 18:57
from __future__ import unicode_literals

from django.db import migrations, models


def load_man_periodo_loaddata_from_fixture(apps, schema_editor):
    from django.core.management import call_command
    call_command("loaddata", "0017_fo2_man_periodo_loaddata")


def delete_man_periodo_loaddata(apps, schema_editor):
    Periodo = apps.get_model("manutencao", "Periodo")
    Periodo.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0016_periodo'),
    ]

    operations = [
        migrations.RunPython(
            load_man_periodo_loaddata_from_fixture,
            delete_man_periodo_loaddata),
    ]
