# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-07-15 19:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0018_rotina_periodo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Periodo',
            new_name='Frequencia',
        ),
        migrations.RenameField(
            model_name='rotina',
            old_name='periodo',
            new_name='frequencia',
        ),
    ]
