# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-07-15 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0019_rename_periodo_to_frequencia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frequencia',
            options={'verbose_name': 'Frequência'},
        ),
        migrations.AlterModelTable(
            name='frequencia',
            table='fo2_man_frequencia',
        ),
    ]
