# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-07-15 19:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0020_rename_table_to_fo2_man_frequencia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rotinapasso',
            options={
                'verbose_name': 'Passo de rotina de manutenção',
                'verbose_name_plural': 'Passos de rotinas de manutenção'
            },
        ),
    ]
