# Generated by Django 2.1.15 on 2022-05-10 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0025_os'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividademetrica',
            name='atividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manutencao.Atividade'),
        ),
        migrations.AlterField(
            model_name='frequencia',
            name='unidade_tempo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manutencao.UnidadeTempo', verbose_name='Unidade de tempo'),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='tipo_maquina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manutencao.TipoMaquina', verbose_name='Tipo de máquina'),
        ),
        migrations.AlterField(
            model_name='os',
            name='maquina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manutencao.Maquina', verbose_name='máquina'),
        ),
        migrations.AlterField(
            model_name='os',
            name='rotina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manutencao.Rotina'),
        ),
        migrations.AlterField(
            model_name='os',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.AlterField(
            model_name='rotina',
            name='frequencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='manutencao.Frequencia', verbose_name='Período'),
        ),
        migrations.AlterField(
            model_name='rotina',
            name='tipo_maquina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manutencao.TipoMaquina', verbose_name='Tipo de máquina'),
        ),
        migrations.AlterField(
            model_name='rotinapasso',
            name='atividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manutencao.Atividade'),
        ),
        migrations.AlterField(
            model_name='rotinapasso',
            name='rotina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manutencao.Rotina'),
        ),
        migrations.AlterField(
            model_name='usuariotipomaquina',
            name='tipo_maquina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manutencao.TipoMaquina', verbose_name='Tipo de máquina'),
        ),
        migrations.AlterField(
            model_name='usuariotipomaquina',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
    ]
