# Generated by Django 3.2.16 on 2023-06-27 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0026_manutencao_protect'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubtipoMaquina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=20)),
                ('slug', models.SlugField()),
                ('descricao', models.CharField(max_length=250, verbose_name='Descrição')),
                ('tipo_maquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manutencao.tipomaquina', verbose_name='Tipo de máquina')),
            ],
            options={
                'verbose_name': 'Subtipo de máquina',
                'verbose_name_plural': 'Subtipos de máquinas',
                'db_table': 'fo2_man_subtipo_maquina',
            },
        ),
    ]
