# Generated by Django 3.2.16 on 2023-06-27 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0027_subtipomaquina'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='subtipo_maquina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='manutencao.subtipomaquina', verbose_name='Subtipo de máquina'),
        ),
    ]
