# Generated by Django 3.2.16 on 2023-06-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0029_alter_maquina_tipo_maquina'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='maquina',
            constraint=models.CheckConstraint(check=models.Q(('tipo_maquina__isnull', False), ('subtipo_maquina__isnull', False), _connector='OR'), name='not_both_null'),
        ),
    ]
