# Generated by Django 3.2.16 on 2023-06-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0030_maquina_not_both_null'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='maquina',
            constraint=models.CheckConstraint(check=models.Q(('tipo_maquina__isnull', True), ('subtipo_maquina__isnull', True), _connector='OR'), name='not_both_not_null'),
        ),
    ]
