from .analise_modelo import *
from .estoque import *
from .devolucao_para_meta import *
from .faturamento_para_meta import *
from .meta_no_ano import *
from .painel_meta_faturamento import *
from .tabela_de_preco import *
from .vendas import *
from .vendas_por_modelo import *
from .views import *
