from django.db import models


class dis_dup(models.Model):
    d_dupnum = models.CharField(db_index=True, max_length=7)
    d_fatnum = models.IntegerField()
    d_cgc = models.CharField(max_length=14)
    d_pednum = models.IntegerField()
    d_valor = models.DecimalField(max_digits=9, decimal_places=2)
    d_dvenc = models.DateField()
    d_dfat = models.DateField()
    d_dcanc = models.DateField()
    d_dpago = models.DateField()
    d_vpago = models.DecimalField(max_digits=9, decimal_places=2)
    d_icm = models.IntegerField()
    d_stat = models.CharField(max_length=1)
    d_statori = models.CharField(max_length=1)
    d_op = models.CharField(max_length=2)
    d_banco = models.CharField(max_length=3)
    d_desconto = models.CharField(max_length=1)
    d_cpag = models.CharField(max_length=1)
    d_cond = models.IntegerField()
    d_qtd = models.IntegerField()
    d_qtdfat = models.IntegerField()
    d_caixas = models.IntegerField()
    d_pesbru = models.DecimalField(max_digits=7, decimal_places=2)
    d_juros = models.DecimalField(max_digits=5, decimal_places=2)
    d_desc = models.DecimalField(max_digits=4, decimal_places=2)
    d_descf1 = models.DecimalField(max_digits=4, decimal_places=2)
    d_descf2 = models.DecimalField(max_digits=4, decimal_places=2)
    d_tipdescf = models.CharField(max_length=1)
    d_repr = models.CharField(max_length=4)
    d_comi = models.DecimalField(max_digits=3, decimal_places=1)
    d_codfis = models.CharField(max_length=4)
    d_transp = models.CharField(max_length=2)
    d_pc = models.DecimalField(max_digits=10, decimal_places=4)
    d_protest = models.CharField(max_length=1)
    d_especial = models.CharField(max_length=1)
    d_777 = models.DecimalField(max_digits=9, decimal_places=2)
    d_qtd777 = models.IntegerField()
    d_obs = models.CharField(max_length=14)
    d_aux = models.CharField(max_length=1)
    d_978 = models.DecimalField(max_digits=9, decimal_places=2)
    d_qtd978 = models.IntegerField()
    rec_ver = models.IntegerField()
    d_tipocanc = models.IntegerField()
    d_prortip = models.CharField(max_length=1)
    calc_cgc = models.CharField(max_length=8)
    d_modfrete = models.CharField(max_length=1)
    f_f1 = models.CharField(max_length=1)
    d_repr2 = models.CharField(max_length=3)
    d_dentr = models.DateField()
    d_dsaida = models.DateField()
    d_snagenda = models.CharField(max_length=1)
    d_snentreg = models.CharField(max_length=1)
    d_dxmlsent = models.DateField()
    d_dtrem = models.DateField()
    d_arqrem = models.CharField(max_length=8)
    d_dvencori = models.DateField()
    d_dvencrem = models.DateField()
    d_dxmlsend = models.DateField()
    d_xmlenvia = models.CharField(max_length=1)
    d_obsentr = models.CharField(max_length=80)
    d_descfat = models.DecimalField(max_digits=9, decimal_places=2)

    class Meta:
        db_table = "tussor_dis_dup"


